/* Кузница — хроники Системы.
   Короткие истории про людей, которые вытащили себя ежедневной работой.
   Открываются по одной за тренировку. Фотографии не лежат в репозитории:
   они подгружаются с Викимедиа, автор и лицензия подписаны в окне.
   Анекдотичные истории поданы как «по его рассказам» — документальными
   их выдавать нельзя. */

var HERO_PHOTOS = {
  ali: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/89/Muhammad_Ali_NYWTS.jpg/330px-Muhammad_Ali_NYWTS.jpg", art: "Ira Rosenberg", lic: "Public domain", page: "https://ru.wikipedia.org/wiki/%D0%90%D0%BB%D0%B8%2C_%D0%9C%D1%83%D1%85%D0%B0%D0%BC%D0%BC%D0%B5%D0%B4" },
  arnold: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e3/Arnold_Schwarzenegger_-_Austrian_World_Summit_2026_BHO-2906.jpg/330px-Arnold_Schwarzenegger_-_Austrian_World_Summit_2026_BHO-2906.jpg", art: "Bernhard Holub", lic: "CC BY-SA 4.0", page: "https://ru.wikipedia.org/wiki/%D0%A8%D0%B2%D0%B0%D1%80%D1%86%D0%B5%D0%BD%D0%B5%D0%B3%D0%B3%D0%B5%D1%80%2C_%D0%90%D1%80%D0%BD%D0%BE%D0%BB%D1%8C%D0%B4" },
  atlas: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4a/Charles_Atlas_-_Physical_Culture_Magazine_-_October_1921.JPG/330px-Charles_Atlas_-_Physical_Culture_Magazine_-_October_1921.JPG", art: "Physical Culture Magazine", lic: "Public domain", page: "https://ru.wikipedia.org/wiki/%D0%90%D1%82%D0%BB%D0%B0%D1%81%2C_%D0%A7%D0%B0%D1%80%D0%BB%D1%8C%D0%B7" },
  bolt: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f6/Bolt_conquista_tricampeonato_tamb%C3%A9m_nos_200_metros_1038888-18.08.2016_ffz-8336.jpg/330px-Bolt_conquista_tricampeonato_tamb%C3%A9m_nos_200_metros_1038888-18.08.2016_ffz-8336.jpg", art: "Fernando Frazão/Agência Brasil", lic: "CC BY 3.0 br", page: "https://ru.wikipedia.org/wiki/%D0%91%D0%BE%D0%BB%D1%82%2C_%D0%A3%D1%81%D1%8D%D0%B9%D0%BD" },
  bruce: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/ca/Bruce_Lee_1973.jpg/330px-Bruce_Lee_1973.jpg", art: "National General Pictures", lic: "Public domain", page: "https://ru.wikipedia.org/wiki/%D0%9B%D0%B8%2C_%D0%91%D1%80%D1%8E%D1%81" },
  bubka: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/ba/Sergey_Bubka_2013-01-08.jpg/330px-Sergey_Bubka_2013-01-08.jpg", art: "Doha Stadium Plus Qatar Photograph: Vinod Divakaran ( www.do", lic: "CC BY 2.0", page: "https://ru.wikipedia.org/wiki/%D0%91%D1%83%D0%B1%D0%BA%D0%B0%2C_%D0%A1%D0%B5%D1%80%D0%B3%D0%B5%D0%B9_%D0%9D%D0%B0%D0%B7%D0%B0%D1%80%D0%BE%D0%B2%D0%B8%D1%87" },
  coleman: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fb/Ronnie_Coleman_8_x_Mr_Olympia_-_2009_-_5.png/330px-Ronnie_Coleman_8_x_Mr_Olympia_-_2009_-_5.png", art: "www.localfitness.com.au", lic: "CC BY-SA 3.0", page: "https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D1%83%D0%BB%D0%BC%D1%8D%D0%BD%2C_%D0%A0%D0%BE%D0%BD%D0%BD%D0%B8" },
  fedor: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d8/Fedor_Emelianenko_Dec_2015.jpg/330px-Fedor_Emelianenko_Dec_2015.jpg", art: "Bruno Massami", lic: "CC BY 3.0", page: "https://ru.wikipedia.org/wiki/%D0%95%D0%BC%D0%B5%D0%BB%D1%8C%D1%8F%D0%BD%D0%B5%D0%BD%D0%BA%D0%BE%2C_%D0%A4%D1%91%D0%B4%D0%BE%D1%80_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B8%D1%87" },
  ferrigno: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/73/Lou_Ferrigno_2018.jpg/330px-Lou_Ferrigno_2018.jpg", art: "Toglenn", lic: "CC BY-SA 4.0", page: "https://ru.wikipedia.org/wiki/%D0%A4%D0%B5%D1%80%D1%80%D0%B8%D0%BD%D1%8C%D0%BE%2C_%D0%9B%D1%83" },
  foreman: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/50/George_Foreman_071516.jpg/330px-George_Foreman_071516.jpg", art: "Gage Skidmore from Peoria, AZ, United States of America", lic: "CC BY-SA 2.0", page: "https://ru.wikipedia.org/wiki/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0%D0%BD%2C_%D0%94%D0%B6%D0%BE%D1%80%D0%B4%D0%B6" },
  goggins: { src: "https://upload.wikimedia.org/wikipedia/commons/e/e3/DavidGogginsMay08.jpg", art: "Paul Rudman at https://www.flickr.com/photos/thecanonrattman", lic: "CC BY-SA 3.0", page: "https://ru.wikipedia.org/wiki/%D0%93%D0%BE%D0%B3%D0%B3%D0%B8%D0%BD%D1%81%2C_%D0%94%D1%8D%D0%B2%D0%B8%D0%B4" },
  hackensch: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/10/Georg_Hackenschmidt_ca._1905.jpg/330px-Georg_Hackenschmidt_ca._1905.jpg", art: "Unknown author Unknown author", lic: "Public domain", page: "https://ru.wikipedia.org/wiki/%D0%93%D0%B0%D0%BA%D0%BA%D0%B5%D0%BD%D1%88%D0%BC%D0%B8%D0%B4%D1%82%2C_%D0%93%D0%B5%D0%BE%D1%80%D0%B3" },
  hall: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/92/Eddie_Hall.jpg/330px-Eddie_Hall.jpg", art: "Quejaytee", lic: "CC BY-SA 4.0", page: "https://ru.wikipedia.org/wiki/%D0%A5%D0%BE%D0%BB%D0%BB%2C_%D0%AD%D0%B4%D0%B4%D0%B8" },
  isinbaeva: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/28/%D0%95%D0%BB%D0%B5%D0%BD%D0%B0_%D0%98%D1%81%D0%B8%D0%BD%D0%B1%D0%B0%D0%B5%D0%B2_%D0%B2_%D0%9A%D1%80%D0%B5%D0%BC%D0%BB%D0%B5.jpg/330px-%D0%95%D0%BB%D0%B5%D0%BD%D0%B0_%D0%98%D1%81%D0%B8%D0%BD%D0%B1%D0%B0%D0%B5%D0%B2_%D0%B2_%D0%9A%D1%80%D0%B5%D0%BC%D0%BB%D0%B5.jpg", art: "Russian Presidential Press and Information Office", lic: "CC BY 4.0", page: "https://ru.wikipedia.org/wiki/%D0%98%D1%81%D0%B8%D0%BD%D0%B1%D0%B0%D0%B5%D0%B2%D0%B0%2C_%D0%95%D0%BB%D0%B5%D0%BD%D0%B0_%D0%93%D0%B0%D0%B4%D0%B6%D0%B8%D0%B5%D0%B2%D0%BD%D0%B0" },
  jackie: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/35/Jackie_Chan.jpg/330px-Jackie_Chan.jpg", art: "Segolene Liger", lic: "CC BY-SA 4.0", page: "https://ru.wikipedia.org/wiki/%D0%A7%D0%B0%D0%BD%2C_%D0%94%D0%B6%D0%B5%D0%BA%D0%B8" },
  jackman: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/02/Hugh_Jackman_by_Gage_Skidmore_3.jpg/330px-Hugh_Jackman_by_Gage_Skidmore_3.jpg", art: "Gage Skidmore", lic: "CC BY-SA 3.0", page: "https://ru.wikipedia.org/wiki/%D0%94%D0%B6%D0%B5%D0%BA%D0%BC%D0%B0%D0%BD%2C_%D0%A5%D1%8C%D1%8E" },
  jordan: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ae/Michael_Jordan_in_2014.jpg/330px-Michael_Jordan_in_2014.jpg", art: "DOD photo by D. Myles Cullen", lic: "Public domain", page: "https://ru.wikipedia.org/wiki/%D0%94%D0%B6%D0%BE%D1%80%D0%B4%D0%B0%D0%BD%2C_%D0%9C%D0%B0%D0%B9%D0%BA%D0%BB" },
  karelin: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/42/Aleksandr_Karelin_WCG-2013.jpg/330px-Aleksandr_Karelin_WCG-2013.jpg", art: "Sokolov Aleksey", lic: "CC BY-SA 3.0", page: "https://ru.wikipedia.org/wiki/%D0%9A%D0%B0%D1%80%D0%B5%D0%BB%D0%B8%D0%BD%2C_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80%D0%BE%D0%B2%D0%B8%D1%87" },
  khabib: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/34/Khabib_nurmagomedov.jpg/330px-Khabib_nurmagomedov.jpg", art: "Airotcivss", lic: "CC BY-SA 4.0", page: "https://ru.wikipedia.org/wiki/%D0%9D%D1%83%D1%80%D0%BC%D0%B0%D0%B3%D0%BE%D0%BC%D0%B5%D0%B4%D0%BE%D0%B2%2C_%D0%A5%D0%B0%D0%B1%D0%B8%D0%B1_%D0%90%D0%B1%D0%B4%D1%83%D0%BB%D0%BC%D0%B0%D0%BD%D0%B0%D0%BF%D0%BE%D0%B2%D0%B8%D1%87" },
  kobe: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/82/Kobe_Bryant_2015.jpg/330px-Kobe_Bryant_2015.jpg", art: "Keith Allison from Hanover, MD, USA", lic: "CC BY-SA 2.0", page: "https://ru.wikipedia.org/wiki/%D0%91%D1%80%D0%B0%D0%B9%D0%B0%D0%BD%D1%82%2C_%D0%9A%D0%BE%D0%B1%D0%B8" },
  pacquiao: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b6/Pacquiao_and_Didal_%28cropped%29.jpg/330px-Pacquiao_and_Didal_%28cropped%29.jpg", art: "Avito C. Dalan for the Philippine News Agency", lic: "Public domain", page: "https://ru.wikipedia.org/wiki/%D0%9F%D0%B0%D0%BA%D1%8C%D1%8F%D0%BE%2C_%D0%9C%D1%8D%D0%BD%D0%BD%D0%B8" },
  phelps: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c6/Michael_Phelps_August_2016.jpg/330px-Michael_Phelps_August_2016.jpg", art: "Agência Brasil Fotografias", lic: "CC BY 2.0", page: "https://ru.wikipedia.org/wiki/%D0%A4%D0%B5%D0%BB%D0%BF%D1%81%2C_%D0%9C%D0%B0%D0%B9%D0%BA%D0%BB" },
  platz: { src: "https://upload.wikimedia.org/wikipedia/commons/b/b7/13_Maggio_1995_Paolo_Tassetto_con_Tom_Platz%2C_Mr._Universo_%28cropped%29.JPG", art: "Ciuffo", lic: "CC BY-SA 4.0", page: "https://ru.wikipedia.org/wiki/%D0%9F%D0%BB%D0%B0%D1%82%D1%86%2C_%D0%A2%D0%BE%D0%BC" },
  poddubny: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6d/Ivan_Poddubny_1911_colorized.png/330px-Ivan_Poddubny_1911_colorized.png", art: "Colorized by Google Gemini, by Nikita Andreev", lic: "Public domain", page: "https://ru.wikipedia.org/wiki/%D0%9F%D0%BE%D0%B4%D0%B4%D1%83%D0%B1%D0%BD%D1%8B%D0%B9%2C_%D0%98%D0%B2%D0%B0%D0%BD_%D0%9C%D0%B0%D0%BA%D1%81%D0%B8%D0%BC%D0%BE%D0%B2%D0%B8%D1%87" },
  reeves: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f1/Stevereeves1990_CROP.jpg/330px-Stevereeves1990_CROP.jpg", art: "Dotty'sgoinglikethis ; crop by Andy Mabbett", lic: "CC BY-SA 3.0", page: "https://ru.wikipedia.org/wiki/%D0%A0%D0%B8%D0%B2%D0%B7%2C_%D0%A1%D1%82%D0%B8%D0%B2" },
  rock: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9d/Dwayne_Johnson-1809_%28cropped%29.jpg/330px-Dwayne_Johnson-1809_%28cropped%29.jpg", art: "Harald Krichel", lic: "CC BY-SA 4.0", page: "https://ru.wikipedia.org/wiki/%D0%94%D0%B6%D0%BE%D0%BD%D1%81%D0%BE%D0%BD%2C_%D0%94%D1%83%D1%8D%D0%B9%D0%BD" },
  ronaldo: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bb/Cristiano_Ronaldo_Croatia_v_Portugal_2_July_2026-154%28cropped%29.jpg/330px-Cristiano_Ronaldo_Croatia_v_Portugal_2_July_2026-154%28cropped%29.jpg", art: "Bryan Berlin", lic: "CC BY 4.0", page: "https://ru.wikipedia.org/wiki/%D0%9A%D1%80%D0%B8%D1%88%D1%82%D0%B8%D0%B0%D0%BD%D1%83_%D0%A0%D0%BE%D0%BD%D0%B0%D0%BB%D0%B4%D1%83" },
  stallone: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/19/P20251206DT-0472_%28cropped%3B_Sylvester_Stallone%29.jpg/330px-P20251206DT-0472_%28cropped%3B_Sylvester_Stallone%29.jpg", art: "The White House", lic: "Public domain", page: "https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D0%B0%D0%BB%D0%BB%D0%BE%D0%BD%D0%B5%2C_%D0%A1%D0%B8%D0%BB%D1%8C%D0%B2%D0%B5%D1%81%D1%82%D1%80" },
  statham: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d3/Jason_Statham_2018.jpg/330px-Jason_Statham_2018.jpg", art: "MTV International", lic: "CC BY 3.0", page: "https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D0%B5%D0%B9%D1%82%D0%B5%D0%BC%2C_%D0%94%D0%B6%D0%B5%D0%B9%D1%81%D0%BE%D0%BD" },
  tyson: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ee/Mike_Tyson_Photo_Op_GalaxyCon_Austin_2023.jpg/330px-Mike_Tyson_Photo_Op_GalaxyCon_Austin_2023.jpg", art: "Super Festivals", lic: "CC BY 2.0", page: "https://ru.wikipedia.org/wiki/%D0%A2%D0%B0%D0%B9%D1%81%D0%BE%D0%BD%2C_%D0%9C%D0%B0%D0%B9%D0%BA" },
  vlasov: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f1/Yury_Vlasov_1960.jpg/330px-Yury_Vlasov_1960.jpg", art: "Unknown author Unknown author", lic: "Public domain", page: "https://ru.wikipedia.org/wiki/%D0%92%D0%BB%D0%B0%D1%81%D0%BE%D0%B2%2C_%D0%AE%D1%80%D0%B8%D0%B9_%D0%9F%D0%B5%D1%82%D1%80%D0%BE%D0%B2%D0%B8%D1%87" },
  zass: { src: "https://upload.wikimedia.org/wikipedia/commons/e/ea/%D0%90._%D0%98._%D0%97%D0%B0%D1%81%D1%81.jpg", art: "Vyhuholevich", lic: "CC BY-SA 4.0", page: "https://ru.wikipedia.org/wiki/%D0%97%D0%B0%D1%81%D1%81%2C_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87" },
  alekseev: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/51/Vasily_Alekseyev_1970.jpg/330px-Vasily_Alekseyev_1970.jpg", art: "Unknown author Unknown author", lic: "Public domain", page: "https://ru.wikipedia.org/wiki/%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B5%D0%B2%2C_%D0%92%D0%B0%D1%81%D0%B8%D0%BB%D0%B8%D0%B9_%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87" },
  amosov: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c3/Nikolai_Amosov_-_Soviet_Life%2C_October_1984.jpg/330px-Nikolai_Amosov_-_Soviet_Life%2C_October_1984.jpg", art: "Published by the Embassy of the Union of Soviet Socialist Republics to", lic: "Public domain", page: "https://ru.wikipedia.org/wiki/%D0%90%D0%BC%D0%BE%D1%81%D0%BE%D0%B2%2C_%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9_%D0%9C%D0%B8%D1%85%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2%D0%B8%D1%87" },
  anderson: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f9/Paul_Anderson%2C_durante_lo_squat_con_una_ruota_di_carro.jpg/330px-Paul_Anderson%2C_durante_lo_squat_con_una_ruota_di_carro.jpg", art: "Andrea787878", lic: "Public domain", page: "https://en.wikipedia.org/wiki/Paul_Anderson_(weightlifter)" },
  bale: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0a/Christian_Bale-7837.jpg/330px-Christian_Bale-7837.jpg", art: "Harald Krichel", lic: "CC BY-SA 4.0", page: "https://ru.wikipedia.org/wiki/%D0%91%D0%B5%D0%B9%D0%BB%2C_%D0%9A%D1%80%D0%B8%D1%81%D1%82%D0%B8%D0%B0%D0%BD" },
  baryshnikov: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7b/Mikhail_Baryshnikov.jpg/330px-Mikhail_Baryshnikov.jpg", art: "Saeima", lic: "CC BY-SA 2.0", page: "https://ru.wikipedia.org/wiki/%D0%91%D0%B0%D1%80%D1%8B%D1%88%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2%2C_%D0%9C%D0%B8%D1%85%D0%B0%D0%B8%D0%BB_%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B5%D0%B2%D0%B8%D1%87" },
  bikila: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3b/Abebe_Bikila_1968c.jpg/330px-Abebe_Bikila_1968c.jpg", art: "Jack de Nijs for Anefo", lic: "CC0", page: "https://ru.wikipedia.org/wiki/%D0%90%D0%B1%D0%B5%D0%B1%D0%B5_%D0%91%D0%B8%D0%BA%D0%B8%D0%BB%D0%B0" },
  biles: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f6/Simone_Biles_National_Team_2024.jpg/330px-Simone_Biles_National_Team_2024.jpg", art: "Ocoudis", lic: "CC BY-SA 4.0", page: "https://ru.wikipedia.org/wiki/%D0%91%D0%B0%D0%B9%D0%BB%D0%B7%2C_%D0%A1%D0%B8%D0%BC%D0%BE%D0%BD%D0%B0" },
  bjornsson: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f8/Bj%C3%B6rnsson_Arnold_Classic_2017_%28cropped_2%29.jpg/330px-Bj%C3%B6rnsson_Arnold_Classic_2017_%28cropped_2%29.jpg", art: "Paula R. Lively from Zanesville", lic: "CC BY 2.0", page: "https://en.wikipedia.org/wiki/Haf%C3%BE%C3%B3r_J%C3%BAl%C3%ADus_Bj%C3%B6rnsson" },
  cavill: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/30/Henry_Cavill_%2848417913146%29_%28cropped%29.jpg/330px-Henry_Cavill_%2848417913146%29_%28cropped%29.jpg", art: "Gage Skidmore from Peoria, AZ, United States of America", lic: "CC BY-SA 2.0", page: "https://ru.wikipedia.org/wiki/%D0%9A%D0%B0%D0%B2%D0%B8%D0%BB%D0%BB%2C_%D0%93%D0%B5%D0%BD%D1%80%D0%B8" },
  columbu: { src: "https://upload.wikimedia.org/wikipedia/commons/c/c6/Franco_Columbu_anni_70.jpg", art: "Unknown author Unknown author", lic: "Public domain", page: "https://en.wikipedia.org/wiki/Franco_Columbu" },
  crews: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/58/Terry_Crews_by_Gage_Skidmore_5.jpg/330px-Terry_Crews_by_Gage_Skidmore_5.jpg", art: "Gage Skidmore", lic: "CC BY-SA 3.0", page: "https://ru.wikipedia.org/wiki/%D0%9A%D1%80%D1%8E%D1%81%2C_%D0%A2%D0%B5%D1%80%D1%80%D0%B8" },
  cruise: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/23/Tom_Cruise_at_53rd_Saturn_Awards_2026-01.jpg/330px-Tom_Cruise_at_53rd_Saturn_Awards_2026-01.jpg", art: "Kevin Paul", lic: "CC BY 4.0", page: "https://ru.wikipedia.org/wiki/%D0%9A%D1%80%D1%83%D0%B7%2C_%D0%A2%D0%BE%D0%BC" },
  djokovic: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/48/Novak_Djokovi%C4%87_Trophy_Wimbledon_2019-croped_and_edited.jpg/330px-Novak_Djokovi%C4%87_Trophy_Wimbledon_2019-croped_and_edited.jpg", art: "Peter Menzel , edited by Petar Milošević", lic: "CC BY-SA 2.0", page: "https://ru.wikipedia.org/wiki/%D0%94%D0%B6%D0%BE%D0%BA%D0%BE%D0%B2%D0%B8%D1%87%2C_%D0%9D%D0%BE%D0%B2%D0%B0%D0%BA" },
  donnie: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/19/Donnie_Yen_20250323.jpg/330px-Donnie_Yen_20250323.jpg", art: "Will629", lic: "CC0", page: "https://ru.wikipedia.org/wiki/%D0%99%D0%B5%D0%BD%2C_%D0%94%D0%BE%D0%BD%D0%BD%D0%B8" },
  franklin: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/87/Joseph_Siffrein_Duplessis_-_Benjamin_Franklin_-_Google_Art_Project.jpg/330px-Joseph_Siffrein_Duplessis_-_Benjamin_Franklin_-_Google_Art_Project.jpg", art: "Joseph-Siffred Duplessis", lic: "Public domain", page: "https://ru.wikipedia.org/wiki/%D0%A4%D1%80%D0%B0%D0%BD%D0%BA%D0%BB%D0%B8%D0%BD%2C_%D0%91%D0%B5%D0%BD%D0%B4%D0%B6%D0%B0%D0%BC%D0%B8%D0%BD" },
  gagarin: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e6/Yuri_Gagarin_with_awards.jpg/330px-Yuri_Gagarin_with_awards.jpg", art: "Александр Моклецов / СовИнформБюро", lic: "CC BY 4.0", page: "https://ru.wikipedia.org/wiki/%D0%93%D0%B0%D0%B3%D0%B0%D1%80%D0%B8%D0%BD%2C_%D0%AE%D1%80%D0%B8%D0%B9_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B5%D0%B2%D0%B8%D1%87" },
  hemsworth: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/69/Chris_Hemsworth_by_Gage_Skidmore_3.jpg/330px-Chris_Hemsworth_by_Gage_Skidmore_3.jpg", art: "Gage Skidmore", lic: "CC BY-SA 3.0", page: "https://ru.wikipedia.org/wiki/%D0%A5%D0%B5%D0%BC%D1%81%D0%B2%D0%BE%D1%80%D1%82%2C_%D0%9A%D1%80%D0%B8%D1%81" },
  iss: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e1/The_station_pictured_from_the_SpaceX_Crew_Dragon_5_%28cropped%29.jpg/330px-The_station_pictured_from_the_SpaceX_Crew_Dragon_5_%28cropped%29.jpg", art: "NASA", lic: "Public domain", page: "https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D0%B6%D0%B4%D1%83%D0%BD%D0%B0%D1%80%D0%BE%D0%B4%D0%BD%D0%B0%D1%8F_%D0%BA%D0%BE%D1%81%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F_%D1%81%D1%82%D0%B0%D0%BD%D1%86%D0%B8%D1%8F" },
  kant: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/79/Immanuel_Kant_-_Gemaelde_1.jpg/330px-Immanuel_Kant_-_Gemaelde_1.jpg", art: "Johann Gottlieb Becker (1720-1782)", lic: "Public domain", page: "https://ru.wikipedia.org/wiki/%D0%9A%D0%B0%D0%BD%D1%82%2C_%D0%98%D0%BC%D0%BC%D0%B0%D0%BD%D1%83%D0%B8%D0%BB" },
  kasparov: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8e/Garry_Kasparov_European_Union_2023_%28cropped%29.jpg/330px-Garry_Kasparov_European_Union_2023_%28cropped%29.jpg", art: "Lukasz Kobus", lic: "CC BY 4.0", page: "https://ru.wikipedia.org/wiki/%D0%9A%D0%B0%D1%81%D0%BF%D0%B0%D1%80%D0%BE%D0%B2%2C_%D0%93%D0%B0%D1%80%D1%80%D0%B8_%D0%9A%D0%B8%D0%BC%D0%BE%D0%B2%D0%B8%D1%87" },
  kazmaier: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/dd/Bill_Kazmaier.JPG/330px-Bill_Kazmaier.JPG", art: "stu_spivack", lic: "CC BY-SA 2.0", page: "https://ru.wikipedia.org/wiki/%D0%9A%D0%B0%D0%B7%D0%BC%D0%B0%D0%B9%D0%B5%D1%80%2C_%D0%91%D0%B8%D0%BB%D0%BB" },
  keanu: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b4/Keanu_Reeves_at_TIFF_2025_02_%28Cropped%29.jpg/330px-Keanu_Reeves_at_TIFF_2025_02_%28Cropped%29.jpg", art: "Gabriel Hutchinson", lic: "CC BY-SA 4.0", page: "https://ru.wikipedia.org/wiki/%D0%A0%D0%B8%D0%B2%D0%B7%2C_%D0%9A%D0%B8%D0%B0%D0%BD%D1%83" },
  kharlamov: { src: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Valeri_Kharlamov_2023_cover_of_Russia_cr6.jpg", art: "S. Ulyanovsky", lic: "Public domain", page: "https://ru.wikipedia.org/wiki/%D0%A5%D0%B0%D1%80%D0%BB%D0%B0%D0%BC%D0%BE%D0%B2%2C_%D0%92%D0%B0%D0%BB%D0%B5%D1%80%D0%B8%D0%B9_%D0%91%D0%BE%D1%80%D0%B8%D1%81%D0%BE%D0%B2%D0%B8%D1%87" },
  khorkina: { src: "https://upload.wikimedia.org/wikipedia/commons/f/fb/Svetlana_Khorkina_2017.jpg", art: "Department of Information of the Ministry of Defense of Russia", lic: "CC BY 4.0", page: "https://ru.wikipedia.org/wiki/%D0%A5%D0%BE%D1%80%D0%BA%D0%B8%D0%BD%D0%B0%2C_%D0%A1%D0%B2%D0%B5%D1%82%D0%BB%D0%B0%D0%BD%D0%B0_%D0%92%D0%B0%D1%81%D0%B8%D0%BB%D1%8C%D0%B5%D0%B2%D0%BD%D0%B0" },
  kipchoge: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/55/Eliud_Kipchoge_in_Berlin_%28cropped%29.jpg/330px-Eliud_Kipchoge_in_Berlin_%28cropped%29.jpg", art: "Desitlicheresguruweil", lic: "CC BY-SA 4.0", page: "https://ru.wikipedia.org/wiki/%D0%9A%D0%B8%D0%BF%D1%87%D0%BE%D0%B3%D0%B5%2C_%D0%AD%D0%BB%D0%B8%D1%83%D0%B4" },
  klitschko: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cd/Volodymyr_Klychko_%28Vladimir_Klitschko%29_of_Ukraine_at_the_59th_Munich_Security_Conference_in_Munich_on_17_February_2023_-_%28cropped%29.jpg/330px-Volodymyr_Klychko_%28Vladimir_Klitschko%29_of_Ukraine_at_the_59th_Munich_Security_Conference_in_Munich_on_17_February_2023_-_%28cropped%29.jpg", art: "MSC/Kuhlmann", lic: "CC BY 3.0 de", page: "https://ru.wikipedia.org/wiki/%D0%9A%D0%BB%D0%B8%D1%87%D0%BA%D0%BE%2C_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B8%D1%87" },
  lalanne: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0d/Jack_LaLanne_%28cropped%29.jpg/330px-Jack_LaLanne_%28cropped%29.jpg", art: "Nathan Cremisino from Ventura, CA, USA", lic: "CC BY-SA 2.0", page: "https://ru.wikipedia.org/wiki/%D0%9B%D0%B0%D0%BB%D1%8D%D0%B9%D0%BD%2C_%D0%94%D0%B6%D0%B5%D0%BA" },
  latynina: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d8/Larisa_Latynina%2C_2010.jpg/330px-Larisa_Latynina%2C_2010.jpg", art: "Пресс-служба Президента России", lic: "CC BY 4.0", page: "https://ru.wikipedia.org/wiki/%D0%9B%D0%B0%D1%82%D1%8B%D0%BD%D0%B8%D0%BD%D0%B0%2C_%D0%9B%D0%B0%D1%80%D0%B8%D1%81%D0%B0_%D0%A1%D0%B5%D0%BC%D1%91%D0%BD%D0%BE%D0%B2%D0%BD%D0%B0" },
  lundgren: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/08/Dolph_Lundgren_Photo_Op_GalaxyCon_Richmond_2024.jpg/330px-Dolph_Lundgren_Photo_Op_GalaxyCon_Richmond_2024.jpg", art: "Super Festivals from Ft. Lauderdale, USA", lic: "CC BY 2.0", page: "https://ru.wikipedia.org/wiki/%D0%9B%D1%83%D0%BD%D0%B4%D0%B3%D1%80%D0%B5%D0%BD%2C_%D0%94%D0%BE%D0%BB%D1%8C%D1%84" },
  messi: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c8/Leo_Messi_Argentina_v_Egypt_7_July_2026-1.jpg/330px-Leo_Messi_Argentina_v_Egypt_7_July_2026-1.jpg", art: "Bryan Berlin", lic: "CC BY-SA 4.0", page: "https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%81%D1%81%D0%B8%2C_%D0%9B%D0%B8%D0%BE%D0%BD%D0%B5%D0%BB%D1%8C" },
  murakami: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/51/Conversatorio_Haruki_Murakami_%2812_de_12%29_%2845747009452%29_%28cropped%29.jpg/330px-Conversatorio_Haruki_Murakami_%2812_de_12%29_%2845747009452%29_%28cropped%29.jpg", art: "Ministerio Cultura y Patrimonio from Quito, Ecuador", lic: "Public domain", page: "https://ru.wikipedia.org/wiki/%D0%9C%D1%83%D1%80%D0%B0%D0%BA%D0%B0%D0%BC%D0%B8%2C_%D0%A5%D0%B0%D1%80%D1%83%D0%BA%D0%B8" },
  norris: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/30/Chuck_Norris_May_2015.jpg/330px-Chuck_Norris_May_2015.jpg", art: "Staff Sgt. Tony Foster", lic: "Public domain", page: "https://ru.wikipedia.org/wiki/%D0%9D%D0%BE%D1%80%D1%80%D0%B8%D1%81%2C_%D0%A7%D0%B0%D0%BA" },
  nurmi: { src: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Paavo_Nurmi_%28Antwerp_1920%29.jpg", art: "Unknown author Unknown author (Suomen Urheilumuseo)", lic: "Public domain", page: "https://ru.wikipedia.org/wiki/%D0%9D%D1%83%D1%80%D0%BC%D0%B8%2C_%D0%9F%D0%B0%D0%B0%D0%B2%D0%BE" },
  owens: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/19/Jesse_Owens_1936.jpg/330px-Jesse_Owens_1936.jpg", art: "Acme News Photos", lic: "Public domain", page: "https://ru.wikipedia.org/wiki/%D0%9E%D1%83%D1%8D%D0%BD%D1%81%2C_%D0%94%D0%B6%D0%B5%D1%81%D1%81%D0%B8" },
  pavlov: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7d/Ivan_Pavlov_NLM3.jpg/330px-Ivan_Pavlov_NLM3.jpg", art: "Unknown author Unknown author", lic: "Public domain", page: "https://ru.wikipedia.org/wiki/%D0%9F%D0%B0%D0%B2%D0%BB%D0%BE%D0%B2%2C_%D0%98%D0%B2%D0%B0%D0%BD_%D0%9F%D0%B5%D1%82%D1%80%D0%BE%D0%B2%D0%B8%D1%87" },
  pele: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5e/Pele_con_brasil_%28cropped%29.jpg/330px-Pele_con_brasil_%28cropped%29.jpg", art: "Unknown author Unknown author", lic: "Public domain", page: "https://ru.wikipedia.org/wiki/%D0%9F%D0%B5%D0%BB%D0%B5" },
  plisetskaya: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b1/Maya_Plisetskaya_%282009-04-21%29.jpg/330px-Maya_Plisetskaya_%282009-04-21%29.jpg", art: "Unknown author Unknown author", lic: "CC BY 4.0", page: "https://ru.wikipedia.org/wiki/%D0%9F%D0%BB%D0%B8%D1%81%D0%B5%D1%86%D0%BA%D0%B0%D1%8F%2C_%D0%9C%D0%B0%D0%B9%D1%8F_%D0%9C%D0%B8%D1%85%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2%D0%BD%D0%B0" },
  popov: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8e/Alexander_Popov_2008.jpg/330px-Alexander_Popov_2008.jpg", art: "Alexander_Popov_Pékin_2008.jpg : KenChong 一洲 derivative work: Zakke ( ", lic: "CC BY-SA 2.0", page: "https://ru.wikipedia.org/wiki/%D0%9F%D0%BE%D0%BF%D0%BE%D0%B2%2C_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B8%D1%87_(%D0%BF%D0%BB%D0%BE%D0%B2%D0%B5%D1%86)" },
  riner: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7f/Teddy_Riner_Cannes_2016.jpg/330px-Teddy_Riner_Cannes_2016.jpg", art: "Georges Biard", lic: "CC BY-SA 3.0", page: "https://ru.wikipedia.org/wiki/%D0%A0%D0%B8%D0%BD%D0%B5%D1%80%2C_%D0%A2%D0%B5%D0%B4%D0%B4%D0%B8" },
  sandow: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0e/Falk%2C_Benjamin_J._%281853-1925%29_-_Eugen_Sandow_%281867-1925%29.jpg/330px-Falk%2C_Benjamin_J._%281853-1925%29_-_Eugen_Sandow_%281867-1925%29.jpg", art: "Benjamin J. Falk (1853-1925)", lic: "Public domain", page: "https://ru.wikipedia.org/wiki/%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D0%B8%D0%B9_%D0%A1%D0%B0%D0%BD%D0%B4%D0%BE%D0%B2" },
  serena: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4b/Serena_Williams_at_2013_US_Open.jpg/330px-Serena_Williams_at_2013_US_Open.jpg", art: "Edwin Martinez", lic: "CC BY 2.0", page: "https://ru.wikipedia.org/wiki/%D0%A3%D0%B8%D0%BB%D1%8C%D1%8F%D0%BC%D1%81%2C_%D0%A1%D0%B5%D1%80%D0%B5%D0%BD%D0%B0" },
  shaolin: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/38/%E5%B0%91%E6%9E%97%E5%AF%BA.jpg/330px-%E5%B0%91%E6%9E%97%E5%AF%BA.jpg", art: "The original uploader was Baiqitun at Chinese Wikipedia .", lic: "CC BY-SA 3.0", page: "https://ru.wikipedia.org/wiki/%D0%A8%D0%B0%D0%BE%D0%BB%D0%B8%D0%BD%D1%8C" },
  shaw: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/05/Brian_Shaw.jpg/330px-Brian_Shaw.jpg", art: "The White House Office of the Press Secretary", lic: "Public domain", page: "https://ru.wikipedia.org/wiki/%D0%A8%D0%BE%D1%83%2C_%D0%91%D1%80%D0%B0%D0%B9%D0%B0%D0%BD" },
  sumo: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ac/Asashoryu_fight_Jan08.JPG/330px-Asashoryu_fight_Jan08.JPG", art: "Eckhard Pecher User:Arcimboldo", lic: "CC BY 3.0", page: "https://ru.wikipedia.org/wiki/%D0%A1%D1%83%D0%BC%D0%BE" },
  suvorov: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2d/Joseph_Kreutzinger_-_Portrait_of_Count_Alexander_Suvorov_-_WGA12281.jpg/330px-Joseph_Kreutzinger_-_Portrait_of_Count_Alexander_Suvorov_-_WGA12281.jpg", art: "Joseph Kreutzinger", lic: "Public domain", page: "https://ru.wikipedia.org/wiki/%D0%A1%D1%83%D0%B2%D0%BE%D1%80%D0%BE%D0%B2%2C_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%92%D0%B0%D1%81%D0%B8%D0%BB%D1%8C%D0%B5%D0%B2%D0%B8%D1%87" },
  theron: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/73/CharlizeTheron-byPhilipRomano2.jpg/330px-CharlizeTheron-byPhilipRomano2.jpg", art: "PhilipRomano", lic: "CC BY-SA 4.0", page: "https://ru.wikipedia.org/wiki/%D0%A2%D0%B5%D1%80%D0%BE%D0%BD%2C_%D0%A8%D0%B0%D1%80%D0%BB%D0%B8%D0%B7" },
  tolstoy: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/94/L.N.Tolstoy_Prokudin-Gorsky_%28cropped%29.jpg/330px-L.N.Tolstoy_Prokudin-Gorsky_%28cropped%29.jpg", art: "Sergei Prokudin-Gorskii", lic: "Public domain", page: "https://ru.wikipedia.org/wiki/%D0%A2%D0%BE%D0%BB%D1%81%D1%82%D0%BE%D0%B9%2C_%D0%9B%D0%B5%D0%B2_%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B5%D0%B2%D0%B8%D1%87" },
  tonyjaa: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/19/Tony_Jaa_2005.jpg/330px-Tony_Jaa_2005.jpg", art: "Colin Geddes", lic: "CC BY 2.0", page: "https://ru.wikipedia.org/wiki/%D0%A2%D0%BE%D0%BD%D0%B8_%D0%94%D0%B6%D0%B0%D0%B0" },
  tszyu: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7a/Kostya_Tszyu_at_2008.png/330px-Kostya_Tszyu_at_2008.png", art: "Uncle Mong", lic: "CC BY-SA 2.0", page: "https://ru.wikipedia.org/wiki/%D0%A6%D0%B7%D1%8E%2C_%D0%9A%D0%BE%D0%BD%D1%81%D1%82%D0%B0%D0%BD%D1%82%D0%B8%D0%BD_%D0%91%D0%BE%D1%80%D0%B8%D1%81%D0%BE%D0%B2%D0%B8%D1%87" },
  vandamme: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c6/Jean-Claude_Van_Damme_at_Brussels_Comic_Con_2023_DSC19480_Kiri_DxO.jpg/330px-Jean-Claude_Van_Damme_at_Brussels_Comic_Con_2023_DSC19480_Kiri_DxO.jpg", art: "Miguel Discart Kiri Karma (Photos Vrac)", lic: "CC BY-SA 2.0", page: "https://ru.wikipedia.org/wiki/%D0%92%D0%B0%D0%BD_%D0%94%D0%B0%D0%BC%D0%BC%2C_%D0%96%D0%B0%D0%BD-%D0%9A%D0%BB%D0%BE%D0%B4" },
  vitali: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/89/EPP_Congress_2025_Valencia_Day_1_%2854483888272%29_%28cropped%29.jpg/330px-EPP_Congress_2025_Valencia_Day_1_%2854483888272%29_%28cropped%29.jpg", art: "European People's Party", lic: "CC BY 2.0", page: "https://ru.wikipedia.org/wiki/%D0%9A%D0%BB%D0%B8%D1%87%D0%BA%D0%BE%2C_%D0%92%D0%B8%D1%82%D0%B0%D0%BB%D0%B8%D0%B9_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B8%D1%87" },
  yashin: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a3/Lev_Yashin.jpg/330px-Lev_Yashin.jpg", art: "Kroon, Ron for Anefo", lic: "CC BY-SA 3.0 nl", page: "https://ru.wikipedia.org/wiki/%D0%AF%D1%88%D0%B8%D0%BD%2C_%D0%9B%D0%B5%D0%B2_%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87" },
  yates: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/db/Dorian_yates.png/330px-Dorian_yates.png", art: "Beaverino", lic: "CC BY-SA 4.0", page: "https://ru.wikipedia.org/wiki/%D0%99%D0%B5%D0%B9%D1%82%D1%81%2C_%D0%94%D0%BE%D1%80%D0%B8%D0%B0%D0%BD" },
  yeoh: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/68/Michelle_Yeoh-2268.jpg/330px-Michelle_Yeoh-2268.jpg", art: "Harald Krichel", lic: "CC BY-SA 4.0", page: "https://ru.wikipedia.org/wiki/%D0%99%D0%B5%D0%BE%2C_%D0%9C%D0%B8%D1%88%D0%B5%D0%BB%D1%8C" },
  zane: { src: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7c/Frank_Zane_2011_Shankbone.JPG/330px-Frank_Zane_2011_Shankbone.JPG", art: "David Shankbone", lic: "CC BY 3.0", page: "https://ru.wikipedia.org/wiki/%D0%97%D0%B5%D0%B9%D0%BD%2C_%D0%A4%D1%80%D1%8D%D0%BD%D0%BA" },
  zatopek: { src: "https://upload.wikimedia.org/wikipedia/commons/9/94/Fotothek_df_roe-neg_0006305_003_Emil_Z%C3%A1topek-2.jpg", art: "Fotothek_df_roe-neg_0006305_003_Emil_Zátopek.jpg : Roger Rössing deriv", lic: "CC BY-SA 3.0 de", page: "https://ru.wikipedia.org/wiki/%D0%97%D0%B0%D1%82%D0%BE%D0%BF%D0%B5%D0%BA%2C_%D0%AD%D0%BC%D0%B8%D0%BB%D1%8C" }
};

var LEGENDS = [
  { id: "stallone1", hero: "stallone", ic: "🥊", name: "Сильвестр Сталлоне", tag: "«Рокки», 1976",
    text: "Сталлоне был безработным актёром с долгами и сценарием, который написал, по его собственным рассказам, за три дня. Студия предлагала за «Рокки» большие деньги — но с условием, что играть будет звезда. Он отказался. Денег не было настолько, что он продал своего пса Буткуса за 40 долларов, а когда фильм запустили — выкупил обратно.",
    line: "Главная ставка — не на талант, а на отказ соглашаться на «попроще»." },
  { id: "stallone2", hero: "stallone", ic: "🥊", name: "Сильвестр Сталлоне", tag: "«Рокки 4», съёмки боя",
    text: "В сцене с Дольфом Лундгреном Сталлоне попросил бить по-настоящему. Один удар в грудь отправил его в больницу: несколько дней в реанимации, давление на сердце. Выйдя, он вернулся на площадку и доснял бой. Позже говорил, что это была глупость — но именно так снимали кадры, которые до сих пор пересматривают.",
    line: "Цену за результат платят телом. Поэтому технику и разминку не пропускают." },
  { id: "arnold1", hero: "arnold", ic: "🏆", name: "Арнольд Шварценеггер", tag: "Зал, который был закрыт",
    text: "В австрийской деревне зал работал не каждый день. Подростком Арнольд, по его рассказам, пролезал внутрь в выходные — тренироваться было важнее, чем ждать понедельника. Возвращался домой по морозу с ледяными руками, но с выполненной тренировкой.",
    line: "Не ждите удобного дня. Удобных дней не бывает — бывают сделанные." },
  { id: "arnold2", hero: "arnold", ic: "🏆", name: "Арнольд Шварценеггер", tag: "Самоволка ради турнира",
    text: "Служа в армии, Арнольд сбежал из части на юниорский турнир «Мистер Европа» — и выиграл его. Вернулся с кубком и получил неделю гауптвахты. Он всегда говорил, что это было честной сделкой: наказание временно, а титул остался в биографии навсегда.",
    line: "Иногда решает не сила, а готовность оказаться там, где идёт отбор." },
  { id: "arnold3", hero: "arnold", ic: "🏆", name: "Арнольд Шварценеггер", tag: "Ещё один подход",
    text: "Его метод звучит проще некуда: когда мышца просит остановиться, сделать ещё один повтор. Арнольд повторял, что последние два-три повтора — единственные, которые что-то меняют, а остальные — дорога к ним.",
    line: "Тренировка начинается там, где вы обычно её заканчиваете." },
  { id: "jackie1", hero: "jackie", ic: "🐉", name: "Джеки Чан", tag: "Пекинская оперная школа",
    text: "С семи лет Джеки жил в интернате оперной школы: подъём до рассвета, акробатика, растяжка, удары — до поздней ночи, десять лет почти без выходных. За ошибку били палкой. Сам он говорит, что ненавидел это тогда и благодарен сейчас: другого тела у него бы не было.",
    line: "Тело запоминает не один героический день, а десять лет обычных." },
  { id: "jackie2", hero: "jackie", ic: "🐉", name: "Джеки Чан", tag: "Трещина в черепе",
    text: "На съёмках «Доспехов Бога» Джеки сорвался с дерева и ударился головой о камень: трещина в черепе, операция, вмятина у виска осталась на всю жизнь. Через несколько месяцев он снова прыгал сам. Ни одна страховая компания в мире его не страхует.",
    line: "Он не бесстрашный. Он просто возвращается после каждого падения." },
  { id: "bruce1", hero: "bruce", ic: "🔥", name: "Брюс Ли", tag: "Тетради вместо памяти",
    text: "Брюс Ли вёл тетради, куда записывал каждое упражнение, вес и число повторов — как бухгалтер. Отдельно гонял предплечья и хват почти ежедневно, считая, что там рождается скорость удара. Ему приписывают фразу: «Я не боюсь того, кто изучил десять тысяч ударов. Я боюсь того, кто отработал один удар десять тысяч раз».",
    line: "Записанный подход отличается от «вроде позанимался» так же, как удар от замаха." },
  { id: "bruce2", hero: "bruce", ic: "🔥", name: "Брюс Ли", tag: "Спина, которая должна была его остановить",
    text: "В 1970-м Брюс Ли повредил спину на тренировке. Врачи говорили, что о боевых искусствах можно забыть. Полгода он пролежал почти без движения — и за это время исписал тетради, из которых потом собрали «Дао Джит Кун До». Вернулся и снял лучшие свои фильмы.",
    line: "Пауза по болезни — не конец пути, а другая его часть." },
  { id: "ali1", hero: "ali", ic: "🦋", name: "Мохаммед Али", tag: "Счёт начинается с боли",
    text: "Али приписывают слова о приседаниях: считать он начинал только тогда, когда становилось больно, — потому что до этого момента это была не работа, а разминка. Другая его известная фраза: «Я ненавидел каждую минуту тренировок, но говорил себе: потерпи сейчас — и проживёшь остаток жизни чемпионом».",
    line: "Последние два повтора — это и есть вся тренировка." },
  { id: "ali2", hero: "ali", ic: "🦋", name: "Мохаммед Али", tag: "Три с половиной года без ринга",
    text: "Али лишили титула и лицензии на три с половиной года — лучшие годы для боксёра. Он вернулся в 28, проиграл Фрейзеру, продолжил работать и в 32 забрал титул обратно у Формана в Заире. Большинство на его месте закончили бы после первой отмены.",
    line: "Простой — не приговор. Приговор — не вернуться после него." },
  { id: "tyson1", hero: "tyson", ic: "👊", name: "Майк Тайсон", tag: "Скучное расписание",
    text: "Подростком Тайсон жил по расписанию, которое сам называл скучным: сотни отжиманий, приседаний, работы на шею и пресс — каждый день, без выходных и без вдохновения. Ни тренажёров, ни добавок: пол, железо и будильник. К двадцати годам это дало самый молодой чемпионский пояс в тяжёлом весе.",
    line: "Скучная рутина побеждает яркие порывы. Всегда." },
  { id: "tyson2", hero: "tyson", ic: "👊", name: "Майк Тайсон", tag: "Кас Д'Амато",
    text: "Тринадцатилетнего Тайсона из колонии для малолетних привели к старому тренеру Касу Д'Амато. Тот посмотрел пару раундов и сказал: это будущий чемпион мира. Забрал к себе домой, дал режим и правила — и вытащил мальчишку в историю бокса.",
    line: "Иногда нужен всего один человек, который поверит. Чаще — вы сами." },
  { id: "karelin1", hero: "karelin", ic: "🐻", name: "Александр Карелин", tag: "Тринадцать лет без поражений",
    text: "Сибирский борец, трёхкратный олимпийский чемпион, не проигрывавший тринадцать лет. Соперники признавались, что проигрывали ему ещё до свистка — от одного вида человека, который явно работал больше.",
    line: "Погода, настроение и усталость — не участники переговоров." },
  { id: "karelin2", hero: "karelin", ic: "🐻", name: "Александр Карелин", tag: "Обратный пояс",
    text: "Его коронный приём — бросок «обратный пояс» — тяжеловесы считали невозможным: поднять на грудь соперника за сто килограммов и перебросить через себя. Карелин делал это в финалах Олимпиад. Отрабатывал годами, когда трибун ещё не было.",
    line: "Красивое на людях собирается из некрасивого в одиночестве." },
  { id: "vlasov1", hero: "vlasov", ic: "⚙️", name: "Юрий Власов", tag: "Очкарик, который поднял больше всех",
    text: "Юрий Власов вышел на помост в очках и с интеллигентным лицом — и стал сильнейшим человеком планеты, чемпионом Рима-1960. Мальчишка Арнольд Шварценеггер, увидев его выступление, решил заниматься железом всерьёз.",
    line: "Сила не выглядит одинаково. Она выглядит как регулярность." },
  { id: "vlasov2", hero: "vlasov", ic: "⚙️", name: "Юрий Власов", tag: "Сила как порядок",
    text: "Уйдя из спорта, Власов писал книги о том, что сила — это прежде всего порядок: в расписании, в еде, в мыслях. Он считал, что человек ломается не от нагрузки, а от хаоса вокруг неё.",
    line: "Наведите порядок в расписании — вес подтянется следом." },
  { id: "foreman1", hero: "foreman", ic: "🕰", name: "Джордж Форман", tag: "Чемпион в 45",
    text: "Форман ушёл из бокса в 28, растолстел, стал проповедником — и вернулся на ринг в 38, когда все считали это шуткой. В 45 лет он выиграл титул чемпиона мира в тяжёлом весе у соперника на двадцать лет моложе.",
    line: "Поздно начать не бывает. Бывает «так и не начал»." },
  { id: "foreman2", hero: "foreman", ic: "🕰", name: "Джордж Форман", tag: "Проигрыш, который научил",
    text: "В Заире Форман был фаворитом и проиграл Али, вымотавшись о его защиту. Позже он говорил, что именно это поражение научило его терпению — качеству, без которого не было бы возвращения через двадцать лет.",
    line: "Неудачная тренировка — это данные, а не приговор." },
  { id: "rock1", hero: "rock", ic: "🪨", name: "Дуэйн Джонсон", tag: "Семь долларов",
    text: "После травмы и вылета из большого футбола у Джонсона, по его рассказам, осталось семь долларов в кармане. Он вернулся к отцу, начал с нуля и сделал тренировки той единственной вещью, которую невозможно отменить.",
    line: "Когда всё рушится, остаётся то, что вы делаете каждое утро." },
  { id: "rock2", hero: "rock", ic: "🪨", name: "Дуэйн Джонсон", tag: "Железо в фуре",
    text: "На съёмки Джонсон возит собственный зал в фуре — чтобы в чужом городе не было повода пропустить. Тренируется около четырёх утра, до всех дел. Зал называет «Кузницей железного рая».",
    line: "Тренировка до дел — единственная, которую не отменят дела." },
  { id: "jackman1", hero: "jackman", ic: "🐺", name: "Хью Джекман", tag: "Росомаха в пятьдесят",
    text: "Джекман не был спортсменом: к серьёзным весам пришёл поздно, уже актёром, и последнюю «Росомаху» снимал ближе к пятидесяти. Его тренер говорил, что секрета нет — есть график на годы.",
    line: "Ваш соперник — вы сами в прошлый вторник." },
  { id: "jackman2", hero: "jackman", ic: "🐺", name: "Хью Джекман", tag: "Между мюзиклом и клеткой",
    text: "Он годами совмещал роли в мюзиклах с подготовкой к «Людям Икс»: пел на Бродвее вечером и тянул железо утром. Признавался, что главная сложность — не нагрузка, а не бросить, когда график летит.",
    line: "График ломается у всех. Разница в том, возвращаетесь ли вы завтра." },
  { id: "coleman1", hero: "coleman", ic: "🏋️", name: "Ронни Колеман", tag: "Полицейский из Арлингтона",
    text: "Днём Колеман работал патрульным полицейским, вечером шёл в зал и становился сильнейшим бодибилдером планеты — восемь титулов «Мистер Олимпия». Его фраза: «Все хотят быть большими, но никто не хочет поднимать тяжёлое железо».",
    line: "Между «хочу» и «делаю» лежит ровно один подход." },
  { id: "coleman2", hero: "coleman", ic: "🏋️", name: "Ронни Колеман", tag: "Цена рекордов",
    text: "После карьеры Колеман перенёс больше десяти операций на позвоночнике и ходит с трудом. Он говорит, что ни о чём не жалеет, но советует молодым не гнаться за разовым максимумом: тело не возвращает переплату.",
    line: "Лучше плюс один повтор, чем минус одна спина." },
  { id: "poddubny1", hero: "poddubny", ic: "🦬", name: "Иван Поддубный", tag: "Чемпион чемпионов",
    text: "Иван Поддубный не курил и не пил, каждый день работал с гирями и штангой — и выигрывал у молодых борцов, когда ему было за сорок. Его называли «чемпионом чемпионов», и за карьеру он почти не знал поражений в классической борьбе.",
    line: "Регулярность обыгрывает молодость чаще, чем кажется." },
  { id: "poddubny2", hero: "poddubny", ic: "🦬", name: "Иван Поддубный", tag: "Трость со свинцом",
    text: "Рассказывают, что Поддубный всюду ходил с тростью, залитой свинцом: пара килограммов в руке весь день — и кисть работает сама собой. Мелочь, которую он не бросал десятилетиями.",
    line: "Мелкая нагрузка каждый день делает больше, чем подвиг раз в месяц." },
  { id: "zass1", hero: "zass", ic: "⛓", name: "Александр Засс", tag: "Железный Самсон",
    text: "Александр Засс весил всего около 80 килограммов, но гнул подковы и рвал цепи. Он утверждал, что дело не в объёме мышц, а в силе сухожилий, и строил тренировки на статике: держать, тянуть, давить — без больших весов.",
    line: "У вас нет тяжёлого железа? У Засса его тоже не было." },
  { id: "zass2", hero: "zass", ic: "⛓", name: "Александр Засс", tag: "Решётка в плену",
    text: "По его собственным рассказам, в плену Первой мировой он сумел согнуть прутья решётки и бежать — не с первой попытки и не за один день. Проверить это невозможно, но метод, которым он тренировался, он описал и оставил людям.",
    line: "Сила прикладывается долго и в одну точку. Как повторы." },
  { id: "hackensch1", hero: "hackensch", ic: "🦁", name: "Георг Гаккеншмидт", tag: "Русский лев",
    text: "Георг Гаккеншмидт из Тарту стал первым чемпионом мира по вольной борьбе и придумал упражнение, которое сегодня носит его имя — гакк-приседания. Свои схемы он записывал и публиковал: считал, что сила должна быть доступна каждому, а не тайной силачей.",
    line: "Понятная система важнее секретной методики." },
  { id: "fedor1", hero: "fedor", ic: "🛡", name: "Фёдор Емельяненко", tag: "Зал в Старом Осколе",
    text: "Десять лет Фёдор Емельяненко считался лучшим тяжеловесом мира — и тренировался в обычном зале в Старом Осколе: покрышка, кувалда, штанга, канат. Никаких особых условий, о которых потом писали бы журналы.",
    line: "Результат делает не оборудование, а то, сколько раз вы туда пришли." },
  { id: "fedor2", hero: "fedor", ic: "🛡", name: "Фёдор Емельяненко", tag: "Простые вещи",
    text: "Он всегда отвечал на вопросы о секретах одинаково: спать, работать, не пропускать, не жаловаться. Интервью с ним разочаровывали журналистов — чуда в ответах не было.",
    line: "Скучный ответ обычно и есть правильный." },
  { id: "khabib1", hero: "khabib", ic: "🏔", name: "Хабиб Нурмагомедов", tag: "Медвежонок в Дагестане",
    text: "Видео, где девятилетний Хабиб борется с медвежонком, обошло весь мир. За ним — горное село, зал отца и сотни детей, которых Абдулманап тренировал по одной программе: борьба каждый день, без исключений.",
    line: "Среда решает. Если её нет — создайте её себе сами." },
  { id: "khabib2", hero: "khabib", ic: "🏔", name: "Хабиб Нурмагомедов", tag: "29 и ноль",
    text: "Хабиб закончил карьеру непобеждённым — 29 боёв, 29 побед — и ушёл на пике, выполнив обещание, данное матери. Отказаться от денег и титулов ради данного слова оказалось тяжелее любого соперника.",
    line: "Договор с собой — тоже обязательство. Тренировка сегодня — его часть." },
  { id: "ronaldo1", hero: "ronaldo", ic: "⚽", name: "Криштиану Роналду", tag: "Тот, кто остаётся после тренировки",
    text: "Партнёры по командам рассказывают одно и то же: когда все уходят, Роналду остаётся. Дополнительные удары, пресс, восстановление, сон по расписанию несколько раз в день. В тридцать девять он показывает данные, которых нет у двадцатилетних.",
    line: "Разницу делает то, что происходит после обязательной части." },
  { id: "ronaldo2", hero: "ronaldo", ic: "⚽", name: "Криштиану Роналду", tag: "Сердце в пятнадцать",
    text: "В пятнадцать лет у него нашли проблему с сердцем — тахикардию. Операция лазером, несколько дней восстановления, и он вернулся на поле. Врачи разрешили играть, но никто не обещал карьеру.",
    line: "Диагноз меняет план, а не цель." },
  { id: "kobe1", hero: "kobe", ic: "🌅", name: "Коби Брайант", tag: "Четыре утра",
    text: "Коби начинал тренировку в четыре утра и объяснял это математикой: если вы начинаете в четыре, а соперник в десять, за год у вас на сотни часов больше. Догнать такое невозможно — можно только начать так же.",
    line: "Час, которого нет у других, находится только рано утром." },
  { id: "kobe2", hero: "kobe", ic: "🌅", name: "Коби Брайант", tag: "Восемьсот бросков",
    text: "Летом он делал по 800–1000 бросков в день, приезжая в зал раньше персонала. На вопрос, не скучно ли, отвечал, что скучно проигрывать.",
    line: "Повторы — это не рутина. Это и есть игра." },
  { id: "jordan1", hero: "jordan", ic: "🏀", name: "Майкл Джордан", tag: "Его не взяли в команду",
    text: "В пятнадцать лет Майкла не взяли в основной состав школьной команды. Он ушёл домой, заперся в комнате и плакал, а потом стал приходить в зал до уроков. Через два года его знала вся Северная Каролина.",
    line: "Отказ — это дата начала, если после него вы пришли в зал." },
  { id: "jordan2", hero: "jordan", ic: "🏀", name: "Майкл Джордан", tag: "Год в тренажёрке",
    text: "Проиграв «Пистонс», которые били его весь сезон, Джордан впервые пошёл в тренажёрный зал всерьёз и провёл там межсезонье, набрав массу. Следующие титулы взял уже другой игрок — тяжелее и жёстче.",
    line: "Когда техники не хватает, добирают силой. И наоборот." },
  { id: "phelps1", hero: "phelps", ic: "🌊", name: "Майкл Фелпс", tag: "Пять лет без выходных",
    text: "Готовясь к Афинам и Пекину, Фелпс плавал каждый день — включая дни рождения, Рождество и Новый год. Пять лет без единого выходного, по его словам, дали ему фору в те доли секунды, которыми меряются медали.",
    line: "Праздники — тоже дни. Календарь не делает исключений." },
  { id: "phelps2", hero: "phelps", ic: "🌊", name: "Майкл Фелпс", tag: "Мальчик, который не мог усидеть",
    text: "В детстве Фелпсу поставили СДВГ, учителя говорили, что он никогда ни на чём не сосредоточится. Бассейн стал местом, где его энергия наконец пригодилась целиком.",
    line: "То, что мешает в одном месте, может быть топливом в другом." },
  { id: "bolt1", hero: "bolt", ic: "⚡", name: "Усэйн Болт", tag: "Спина самого быстрого человека",
    text: "У Болта сколиоз: одна нога короче другой, спина требует ежедневной работы. Львиная доля его тренировок — не бег, а укрепление корпуса и профилактика. Без этой скучной части не было бы ни одного рекорда.",
    line: "Скучные упражнения держат в строю все остальные." },
  { id: "bubka1", hero: "bubka", ic: "📏", name: "Сергей Бубка", tag: "Тридцать пять рекордов по сантиметру",
    text: "Бубка устанавливал мировой рекорд тридцать пять раз, каждый — плюс один сантиметр. Он мог прыгнуть выше сразу, но выбирал шаг, который повторяем: маленький, надёжный, снова и снова.",
    line: "Ваш плюс один повтор — это его плюс один сантиметр." },
  { id: "isinbaeva1", hero: "isinbaeva", ic: "🕊", name: "Елена Исинбаева", tag: "Из гимнастики в шест",
    text: "В пятнадцать лет Елене сказали, что для спортивной гимнастики она слишком высокая. Она перешла в прыжки с шестом — и установила 28 мировых рекордов. Начинать заново в пятнадцать казалось катастрофой ровно один сезон.",
    line: "Смена снаряда — не потеря лет, а перенос навыка." },
  { id: "pacquiao1", hero: "pacquiao", ic: "🥋", name: "Мэнни Пакьяо", tag: "Босиком на улицах Манилы",
    text: "Пакьяо рос в нищете, продавал пончики на улице и ночевал в картонной коробке, тренировался босиком. Он стал чемпионом мира в восьми весовых категориях — такого не делал никто.",
    line: "Условия никогда не бывают подходящими. Они просто бывают." },
  { id: "goggins1", hero: "goggins", ic: "🧊", name: "Дэвид Гоггинс", tag: "Минус пятьдесят килограммов",
    text: "Чтобы попасть в отбор «морских котиков», Гоггинсу нужно было сбросить около пятидесяти килограммов за три месяца. Он сбрасывал их по восемь часов тренировок в день — велотренажёр, бассейн, бег — и успел к сроку.",
    line: "Срок без плана — мечта. План без дней — тоже." },
  { id: "goggins2", hero: "goggins", ic: "🧊", name: "Дэвид Гоггинс", tag: "4030 подтягиваний",
    text: "Рекорд по подтягиваниям за сутки он взял с третьей попытки: первые две закончились сорванными руками и провалом на глазах у камер. В третий раз сделал 4030 повторов за семнадцать часов.",
    line: "Две неудачи — это ещё не ответ. Это подготовка к третьей попытке." },
  { id: "hall1", hero: "hall", ic: "🪝", name: "Эдди Холл", tag: "Полтонны и цена за них",
    text: "Эдди Холл первым в истории поднял 500 килограммов в становой тяге — и потерял сознание на помосте, с кровью из носа и разорванными сосудами глаз. Он говорит, что это был единственный раз в жизни, и повторять не станет.",
    line: "Разовый максимум красив в записи и дорог для тела." },
  { id: "ferrigno1", hero: "ferrigno", ic: "💚", name: "Лу Ферриньо", tag: "Мальчик, который стал Халком",
    text: "Лу Ферриньо потерял большую часть слуха в младенчестве, в школе его дразнили. Он читал комиксы про Халка и качался в подвале, чтобы стать таким же. Через годы его взяли играть Халка в сериале.",
    line: "То, из-за чего над вами смеялись, может стать вашей ролью." },
  { id: "atlas1", hero: "atlas", ic: "🗿", name: "Чарльз Атлас", tag: "Динамическое напряжение",
    text: "Чарльз Атлас был худым подростком, которого, по легенде, обидели на пляже. Он придумал систему без всякого железа — мышца против мышцы, напряжение против напряжения — и стал самым узнаваемым атлетом Америки, моделью для десятков статуй.",
    line: "Нет веса — есть напряжение. Прогресс всё равно возможен." },
  { id: "statham1", hero: "statham", ic: "🎬", name: "Джейсон Стэйтем", tag: "Прыгун в воду",
    text: "До кино Стэйтем двенадцать лет выступал за сборную Англии по прыжкам в воду. Привычку вести дневник тренировок он перенёс в актёрскую жизнь: каждый день записаны упражнения и время, тренировка не отменяется из-за съёмок.",
    line: "Дневник — причина, по которой вы не соврёте себе через месяц." },
  { id: "reeves1", hero: "reeves", ic: "🏛", name: "Стив Ривз", tag: "Геркулес по расписанию",
    text: "Стив Ривз, первый «Геркулес» экрана, тренировался по строгому графику и считал симметрию важнее массы. Его фотографии висели у Шварценеггера на стене — целое поколение пришло в залы, посмотрев на него.",
    line: "Пропорции строятся годами, а не за курс из шести недель." },
  { id: "platz1", hero: "platz", ic: "🦵", name: "Том Платц", tag: "Человек-ноги",
    text: "Том Платц прославился тем, что тренировал ноги так, как не тренировал никто: приседания до потери счёта, подходы по двадцать и больше повторов, когда все делали по шесть. Его ноги до сих пор считают эталоном.",
    line: "Многоповторка — тоже тяжёлая работа. Спросите у того, кто её делал." },
  { id: "stallone3", hero: "stallone", ic: "🥊", name: "Сильвестр Сталлоне", tag: "Форма к «Рокки 3»",
    text: "К третьему «Рокки» он решил, что герой должен выглядеть иначе, и готовился с Франко Коломбо. По его рассказам, доходило до двух тренировок в день, бега по утрам и жёсткой диеты месяцами. Он признавал позже, что перегнул и загнал себя почти до истощения — но кадры с той формой стали визитной карточкой фильма.",
    line: "Форма — это месяцы однообразной работы, а не неделя подвига." },
  { id: "arnold4", hero: "arnold", ic: "🏆", name: "Арнольд Шварценеггер", tag: "Две тренировки в день",
    text: "В армии он тренировался до подъёма и после отбоя, потому что днём времени не было. Позже в Мюнхене он работал в спортзале и там же жил, чтобы не тратить дорогу. Его правило было простым: если день занят, тренировка не отменяется — она переезжает на то время, которое никто не отнимет.",
    line: "Занятый день — повод передвинуть тренировку, а не отменить её." },
  { id: "arnold5", hero: "arnold", ic: "🏆", name: "Арнольд Шварценеггер", tag: "Он видел результат заранее",
    text: "Перед каждым подходом он, по его словам, представлял мышцу такой, какой хочет её сделать. Это не магия: когда вы знаете, куда идёте, вы не делаете движение «как-нибудь». Он говорил, что скучные подходы превращаются в осмысленные, если держать в голове картину результата.",
    line: "Подход без внимания — просто движение. С вниманием — работа." },
  { id: "jackie4", hero: "jackie", ic: "🐉", name: "Джеки Чан", tag: "Падение в Югославии",
    text: "На съёмках «Доспехов Бога» он прыгал с крепостной стены на дерево, ветка обломилась, и он упал на камни. Трещина в черепе, кусок кости у мозга, экстренная операция в госпитале. Через несколько месяцев он вернулся на площадку и доснял фильм — с дырой в голове, прикрытой пробкой.",
    line: "Возвращение после срыва и есть главная способность." },
  { id: "jackie3", hero: "jackie", ic: "🐉", name: "Джеки Чан", tag: "Список переломов",
    text: "Он перечислял травмы по порядку: нос, скулы, череп, грудина, пальцы, лодыжка, позвоночник. Почти каждый фильм добавлял строчку. И всё же он продолжал ставить трюки сам, потому что считал: зритель чувствует разницу между настоящим и подделкой.",
    line: "Тело помнит всё, поэтому технику и разминку не пропускают." },
  { id: "bruce3", hero: "bruce", ic: "🔥", name: "Брюс Ли", tag: "Десять тысяч раз один удар",
    text: "Ему приписывают фразу: «Я не боюсь того, кто изучил десять тысяч ударов. Я боюсь того, кто отработал один удар десять тысяч раз». Точность цитаты спорна, но его собственные тетради это подтверждают: он годами повторял одни и те же базовые движения, меняя мелочи.",
    line: "Мастерство — это повторение одного движения, а не коллекция новых." },
  { id: "bruce4", hero: "bruce", ic: "🔥", name: "Брюс Ли", tag: "Зал в гараже",
    text: "Большую часть своей силовой работы он делал дома: штанга, гантели, самодельные приспособления, изометрия у стены. Никаких дорогих тренажёров — он считал, что оборудование не делает тело, его делает человек, который приходит к железу каждый день.",
    line: "Снаряд может быть скромным. Регулярность — нет." },
  { id: "ali3", hero: "ali", ic: "🦋", name: "Мохаммед Али", tag: "Бег до рассвета",
    text: "Он бегал в четыре-пять утра, задолго до того, как это стало модным. Объяснял просто: соперник в это время спит, и каждое такое утро — преимущество, которое нельзя отнять. Бег он не любил, но считал его фундаментом: без ног руки в двенадцатом раунде не работают.",
    line: "Преимущество набирается в те часы, когда его никто не видит." },
  { id: "tyson3", hero: "tyson", ic: "👊", name: "Майк Тайсон", tag: "Две тысячи приседаний",
    text: "В годы с Кас Д'Амато его день был расписан по минутам: бег, спарринги, мешок, шея, пресс. Он рассказывал про сотни приседаний и отжиманий ежедневно, без обсуждений и выходных. Скучно, одинаково, каждый день — и именно это сделало его чемпионом в двадцать лет.",
    line: "Чемпионов делает расписание, а не настроение." },
  { id: "karelin3", hero: "karelin", ic: "🐻", name: "Александр Карелин", tag: "Зимой в лесу",
    text: "Он рассказывал, как тренировался в сибирском лесу: таскал по снегу бревно, бегал по сугробам, работал там, где нет ни зала, ни зрителей. Это была не показуха, а необходимость — и привычка, которая потом давала фору на ковре, когда у соперника заканчивались силы.",
    line: "Условия редко бывают удобными. Тренировка от этого не отменяется." },
  { id: "vlasov3", hero: "vlasov", ic: "⚙️", name: "Юрий Власов", tag: "После штанги — книги",
    text: "Он был чемпионом и при этом писал книги, знал языки, разбирался в истории. Считал, что сила без головы коротка: тело рано или поздно сдаст, а то, что человек в себя вложил, останется. Его распорядок дня включал и зал, и письменный стол — каждый день.",
    line: "Сила — часть порядка в жизни, а не замена ему." },
  { id: "foreman3", hero: "foreman", ic: "🕰", name: "Джордж Форман", tag: "Возвращение в тридцать восемь",
    text: "После десяти лет без бокса он вернулся на ринг грузным и медленным, и над ним смеялись. Он не стал догонять свою молодость: сменил стиль на экономный, бил реже, но тяжелее. Через семь лет такой работы он стал самым возрастным чемпионом мира в тяжёлом весе.",
    line: "Возвращаются не в прежнюю форму, а в новую — и это нормально." },
  { id: "rock3", hero: "rock", ic: "🪨", name: "Дуэйн Джонсон", tag: "Четыре утра",
    text: "Его день начинается затемно, потому что это единственное время, которое не отберут съёмки и дела. Он называет это «клубом четырёх утра» и говорит, что дело не в раннем подъёме, а в том, что тренировка должна стоять первой, пока день ещё не начал ломать планы.",
    line: "Поставьте тренировку первой — иначе её вытеснит всё остальное." },
  { id: "coleman3", hero: "coleman", ic: "🏋️", name: "Ронни Колеман", tag: "Смена и зал",
    text: "Восемь лет он совмещал тренировки с работой в полиции Арлингтона: ночная смена, потом зал, потом сон. На вопрос, как он выдерживал, отвечал, что просто не рассматривал вариант пропустить. Титул «Мистера Олимпия» пришёл, когда он всё ещё был действующим полицейским.",
    line: "Совмещать тяжело. Не совмещать — значит не начать вовсе." },
  { id: "poddubny3", hero: "poddubny", ic: "🦬", name: "Иван Поддубный", tag: "Сорок лет на ковре",
    text: "Он боролся до шестидесяти с лишним лет и уходил непобеждённым в своём классе. Секрет, который он называл сам, был скучным: режим, отказ от алкоголя и ежедневная работа с весом. Молодые соперники были быстрее, но у него за спиной были десятилетия ровной нагрузки.",
    line: "Выигрывает не самый быстрый, а тот, кто продержался дольше всех." },
  { id: "zass3", hero: "zass", ic: "⛓", name: "Александр Засс", tag: "Сила без больших мышц",
    text: "Он весил немного и на фоне силачей своего времени выглядел обычно, но рвал цепи и держал на себе лошадь. Его метод — изометрия: давить на неподвижное, напрягать мышцу без движения. Он доказывал, что сила сухожилий важнее объёма и что её можно растить где угодно.",
    line: "Объём впечатляет. Работает сила, набранная постепенно." },
  { id: "fedor3", hero: "fedor", ic: "🛡", name: "Фёдор Емельяненко", tag: "Молот и покрышка",
    text: "В его тренировках не было ничего модного: кувалда по покрышке, гири, бег, борьба в зале без кондиционера. Он говорил, что дорогое оборудование ничего не добавляет человеку, который не готов работать, и ничего не отнимает у того, кто готов.",
    line: "Простые снаряды и постоянство бьют дорогой зал без посещений." },
  { id: "khabib3", hero: "khabib", ic: "🏔", name: "Хабиб Нурмагомедов", tag: "Горы вместо зала",
    text: "В детстве он тренировался в горном селе: борьба на ковре в простом зале, бег по склонам, работа по хозяйству. Отец ставил нагрузку так, что обычная жизнь уже была тренировкой. Позже соперники говорили, что его темп невозможно выдержать — он просто не знал другого.",
    line: "Привычка к нагрузке набирается в быту, а не только в зале." },
  { id: "ronaldo3", hero: "ronaldo", ic: "⚽", name: "Криштиану Роналду", tag: "Сон по расписанию",
    text: "Он относится ко сну как к части тренировки: ранний отбой, несколько коротких дневных сеансов, режим даже в поездках. Говорит, что мышцы растут не на поле, а ночью, и что без сна любая работа превращается в изнашивание. В сорок он всё ещё в составе — во многом поэтому.",
    line: "Сон — часть плана, а не то, что остаётся после всего." },
  { id: "kobe3", hero: "kobe", ic: "🌅", name: "Коби Брайант", tag: "Почему так рано",
    text: "Его спрашивали, зачем начинать в четыре утра. Он объяснял арифметикой: если тренироваться на четыре часа больше в день, за год набегает преимущество, которое соперник уже не отыграет. Не талант, не вдохновение — простое сложение дней.",
    line: "Преимущество — это сложение обычных дней, а не один рывок." },
  { id: "jordan3", hero: "jordan", ic: "🏀", name: "Майкл Джордан", tag: "Матч с температурой",
    text: "В финале 1997 года он вышел на площадку больным, еле держась на ногах, и набрал 38 очков. После финальной сирены его увели с площадки под руки. Он потом говорил, что не считал это героизмом: просто был день игры, а значит нужно было играть.",
    line: "Плохое самочувствие меняет объём работы, а не факт её." },
  { id: "phelps3", hero: "phelps", ic: "🌊", name: "Майкл Фелпс", tag: "Пять лет без единого выходного",
    text: "С 1998 по 2003 год он, по собственным словам, не пропустил ни дня — включая дни рождения и праздники. Тренер объяснял это арифметикой: тот, кто тренируется 365 дней, за год получает на 52 тренировки больше того, кто отдыхает по воскресеньям.",
    line: "Пятьдесят два выходных в год — это пятьдесят два пропуска." },
  { id: "goggins3", hero: "goggins", ic: "🧊", name: "Дэвид Гоггинс", tag: "Сорок процентов",
    text: "Его правило: когда кажется, что сил нет, израсходовано примерно сорок процентов — остальное тело бережёт на всякий случай. Он не предлагает насиловать себя каждый день, но настаивает: границу, которую вы себе назначили, стоит иногда проверять.",
    line: "«Больше не могу» обычно значит «стало неудобно»." },
  { id: "statham2", hero: "statham", ic: "🎬", name: "Джейсон Стэйтем", tag: "Двенадцать лет в сборной",
    text: "До кино он двенадцать лет занимался прыжками в воду и выступал за сборную Великобритании. Это объясняет, почему в кадре он двигается иначе, чем те, кто пришёл в форму за три месяца: у него за спиной годы ежедневных тренировок, начатых в детстве.",
    line: "То, что выглядит как талант, обычно оказывается стажем." },
  { id: "platz2", hero: "platz", ic: "🦵", name: "Том Платц", tag: "Приседания как ритуал",
    text: "Его ноги считались лучшими в истории бодибилдинга, и построены они были на одном упражнении, которое он делал с одержимостью: приседания, подходы до полного отказа, иногда по двадцать с лишним повторов. Он говорил, что любит не результат, а сам момент, когда уже невозможно.",
    line: "Одно упражнение, доведённое до предела, стоит десяти вполсилы." },
  { id: "zatopek1", hero: "zatopek", ic: "🏃", name: "Эмиль Затопек", tag: "Интервалы вместо километров",
    text: "Чешский бегун придумал то, чем сегодня пользуются все: вместо ровных длинных пробежек он делал десятки коротких отрезков с паузами. Над ним смеялись — бегает кругами, задыхается, выглядит мучительно. В 1952 году он выиграл на одной Олимпиаде 5000 м, 10 000 м и марафон, который бежал впервые в жизни.",
    line: "Короткие отрезки с паузами работают лучше, чем долго и вполсилы." },
  { id: "zatopek2", hero: "zatopek", ic: "🏃", name: "Эмиль Затопек", tag: "Тренировка в армейских сапогах",
    text: "Он бегал в тяжёлых ботинках, по снегу, иногда с женой на плечах — просто потому, что под рукой не было ни стадиона, ни инвентаря. Логика была та же, что у любого утяжеления: сделай обычное движение тяжелее, и прогресс пойдёт без нового снаряжения.",
    line: "Нет тяжелее веса — сделайте тяжелее само движение." },
  { id: "kipchoge1", hero: "kipchoge", ic: "📒", name: "Элиуд Кипчоге", tag: "Тетрадь вместо приложений",
    text: "Лучший марафонец в истории ведёт обычные бумажные тетради: каждая тренировка, самочувствие, время. Он перечитывает их годами и говорит, что это честнее памяти. Живёт в простом лагере, сам моет пол по очереди с остальными — без исключений для звезды.",
    line: "Записанная тренировка существует. Незаписанная — нет." },
  { id: "kipchoge2", hero: "kipchoge", ic: "📒", name: "Элиуд Кипчоге", tag: "Восемьдесят процентов",
    text: "Он почти не тренируется на пределе: большая часть работы идёт в спокойном темпе, когда можно разговаривать. Тяжёлые дни редки. Именно это позволяет ему годами не ломаться — пока те, кто выкладывается каждый раз, выбывают из-за травм.",
    line: "Лёгкие дни нужны не для отдыха, а чтобы дожить до тяжёлых." },
  { id: "owens1", hero: "owens", ic: "🥇", name: "Джесси Оуэнс", tag: "Четыре золота в Берлине",
    text: "Сын издольщика из Алабамы, он подрабатывал с детства и тренировался до работы, потому что после сил не оставалось. В 1936 году он выиграл четыре золотые медали на Олимпиаде в Берлине, устроенной как витрина расовой теории. Его результаты сделали эту витрину бессмысленной.",
    line: "Утренняя тренировка — та, которую не отменит остаток дня." },
  { id: "nurmi1", hero: "nurmi", ic: "⏱", name: "Пааво Нурми", tag: "Бегун с секундомером",
    text: "Финн начала прошлого века бегал с часами в руке и раскладывал дистанцию по секундам, когда все полагались на чутьё. Девять олимпийских золотых и двадцать два мировых рекорда — результат не вдохновения, а подсчёта. Он первым превратил тренировку в таблицу.",
    line: "То, что измеряется, растёт. Остальное только кажется." },
  { id: "bikila1", hero: "bikila", ic: "🦶", name: "Абебе Бикила", tag: "Марафон босиком",
    text: "В Риме в 1960 году ему не подошла ни одна пара выданной обуви, и он побежал марафон босиком — и выиграл с мировым рекордом. Через четыре года, за шесть недель до Токио, ему вырезали аппендикс. Он всё равно вышел на старт и выиграл снова.",
    line: "Снаряжение помогает. Решает подготовка." },
  { id: "popov1", hero: "popov", ic: "🏊", name: "Александр Попов", tag: "Возвращение после ножа",
    text: "В 1996 году, через месяц после олимпийского золота, пловца ударили ножом на улице Москвы: повреждены почка и лёгкое, врачи говорили о риске для жизни. Он вернулся в воду и через два года снова выигрывал чемпионаты мира, а потом поехал ещё на две Олимпиады.",
    line: "После вынужденного перерыва возвращаются постепенно — но возвращаются." },
  { id: "latynina1", hero: "latynina", ic: "🎀", name: "Лариса Латынина", tag: "Восемнадцать медалей",
    text: "Её рекорд по олимпийским медалям держался почти полвека, пока его не побил Фелпс. Она выступала в эпоху без спортивной медицины, без восстановительных центров, тренируясь в обычных залах. Говорила, что главный её навык — не талант, а умение приходить на тренировку в любом состоянии.",
    line: "В любом состоянии можно сделать хоть что-то. Ноль — это выбор." },
  { id: "khorkina1", hero: "khorkina", ic: "🤸", name: "Светлана Хоркина", tag: "Слишком высокая для гимнастики",
    text: "Ей говорили, что с её ростом в спортивной гимнастике делать нечего: длинные рычаги мешают вращениям. Вместо того чтобы спорить, она придумала элементы под своё тело — несколько из них теперь носят её имя. Два олимпийских золота на брусьях и три титула абсолютной чемпионки мира.",
    line: "Не подходите под упражнение — подгоните упражнение под себя." },
  { id: "biles1", hero: "biles", ic: "🌟", name: "Симона Байлз", tag: "Она сняла себя с финала",
    text: "В Токио на пике карьеры она отказалась от выступления: потеря ориентации в воздухе, при которой прыжок становится опасным. Её обвиняли в слабости. Через два года она вернулась и снова выиграла всё, доказав, что вовремя остановиться — часть долгой карьеры, а не её конец.",
    line: "Пауза по здоровью — не пропуск, а условие продолжения." },
  { id: "serena1", hero: "serena", ic: "🎾", name: "Серена Уильямс", tag: "Возвращение после родов",
    text: "После тяжёлых родов с осложнениями она неделями не могла нормально ходить. Возвращение заняло месяцы и начиналось с коротких занятий. Через несколько месяцев она играла в финале Уимблдона — не выиграла, но доказала, что путь назад есть даже из очень глубокой ямы.",
    line: "Начинайте с малого объёма. Главное — начать снова." },
  { id: "djokovic1", hero: "djokovic", ic: "🎯", name: "Новак Джокович", tag: "Тренировки под бомбёжками",
    text: "Он рос в Белграде в 1999 году, когда город бомбили: ночь в убежище, утром — на корт, иногда на тот, который накануне пострадал. Тренер говорила, что они специально выбирали самые разбитые площадки, потому что туда не приходили другие. Это стало его школой выносливости.",
    line: "Идеальных условий не будет. Работают в тех, что есть." },
  { id: "djokovic2", hero: "djokovic", ic: "🎯", name: "Новак Джокович", tag: "Он нашёл причину срывов",
    text: "Годами он задыхался в решающих сетах и считал это слабостью характера. Оказалось — непереносимость глютена. После смены питания он выиграл почти всё, что можно. История не про диету, а про то, что «нет сил» иногда означает конкретную причину, которую можно найти.",
    line: "Прежде чем винить волю, проверьте сон, еду и восстановление." },
  { id: "bolt2", hero: "bolt", ic: "⚡", name: "Усэйн Болт", tag: "Скучные годы до рекордов",
    text: "Публика видела расслабленного человека, который шутит перед стартом. За кадром были годы работы над спиной — у него сколиоз, из-за которого техника бега всегда была на грани травмы. Укрепление корпуса занимало больше времени, чем сами спринты.",
    line: "За лёгкостью на публике стоит скучная работа над слабым местом." },
  { id: "tszyu1", hero: "tszyu", ic: "🥊", name: "Костя Цзю", tag: "Переезд без языка и денег",
    text: "Он уехал в Австралию, не зная языка, без контрактов и имени на новом континенте. Тренировался в обычном зале, выступал в андеркартах, годами поднимался с самого низа. Абсолютным чемпионом мира стал через девять лет после переезда — не рывком, а длинной лестницей.",
    line: "Путь наверх почти всегда длиннее, чем кажется со стороны." },
  { id: "klitschko1", hero: "klitschko", ic: "🎓", name: "Владимир Кличко", tag: "Боксёр с диссертацией",
    text: "Он защитил кандидатскую по спортивной науке и подходил к боксу как к расчёту: питание по граммам, сон по часам, спарринги под задачу. Его упрекали в скучном стиле, а он отвечал, что скучный стиль позволил ему держать титулы больше десяти лет без тяжёлых травм.",
    line: "Скучный расчёт обычно переживает яркую импровизацию." },
  { id: "klitschko2", hero: "klitschko", ic: "🎓", name: "Владимир Кличко", tag: "После нокаутов",
    text: "В начале карьеры он несколько раз проигрывал нокаутом, и его списывали — говорили, стеклянная челюсть, дальше ничего не будет. Он сменил тренера, перестроил защиту и следующие девять лет не проигрывал вообще. Поражения оказались не концом, а диагнозом.",
    line: "Проигрыш показывает, что чинить. Это информация, а не приговор." },
  { id: "vitali1", hero: "vitali", ic: "🧱", name: "Виталий Кличко", tag: "Бой на разорванной связке",
    text: "В бою с Льюисом у него была рассечена бровь так, что бой остановили, а в другом бою он продолжал с порванной связкой плеча. Он говорил, что боль терпеть умеет, а вот недоработку — нет: проигрыш из-за травмы он принимал, проигрыш из-за лени — нет.",
    line: "Травма — причина остановиться. Лень — нет." },
  { id: "messi1", hero: "messi", ic: "💉", name: "Лионель Месси", tag: "Уколы каждый вечер",
    text: "В одиннадцать лет ему поставили дефицит гормона роста. Несколько лет он сам делал себе уколы в ногу каждый вечер — сначала в одну, потом в другую. Семья не тянула лечение, и переезд в Барселону случился потому, что клуб согласился его оплачивать.",
    line: "Ежедневное действие, которое никто не видит, и решает всё." },
  { id: "messi2", hero: "messi", ic: "💉", name: "Лионель Месси", tag: "Самый маленький на поле",
    text: "В академии он был заметно ниже сверстников, и это считалось приговором для футболиста. Вместо силовой борьбы он довёл до предела то, что у него было: низкий центр тяжести, первый шаг, обработку мяча. Недостаток стал основой стиля, который не смогли скопировать.",
    line: "Слабое место можно обойти, усилив то, что уже работает." },
  { id: "pele1", hero: "pele", ic: "👑", name: "Пеле", tag: "Мяч из тряпок",
    text: "Он рос в нищете, играл тряпичным свёртком, перевязанным верёвкой, и чистил обувь, чтобы помочь семье. Настоящий мяч появился поздно. Он говорил, что именно эти годы дали ему технику: с плохим мячом приходится быть точнее, чем с хорошим.",
    line: "Плохой инвентарь учит технике. Отсутствие занятий не учит ничему." },
  { id: "yashin1", hero: "yashin", ic: "🧤", name: "Лев Яшин", tag: "Завод до футбола",
    text: "С двенадцати лет он работал на заводе в войну, по многу часов, и в футбол пришёл поздно. В воротах начинал с дубля и ошибок, после которых его едва не отчислили. Единственный вратарь в истории с «Золотым мячом» — результат упрямства, а не раннего таланта.",
    line: "Поздний старт не мешает. Мешает решение, что уже поздно." },
  { id: "kharlamov1", hero: "kharlamov", ic: "❄️", name: "Валерий Харламов", tag: "Порок сердца в детстве",
    text: "В детстве он перенёс ревматизм, и врачи запретили ему спорт. Отец привёл его в хоккейную школу тайком, скрыв диагноз. Через годы он стал одним из лучших нападающих мира — и всю карьеру играл с сердцем, которое ему когда-то запретили нагружать.",
    line: "Нагрузку подбирают под себя, а не отменяют совсем." },
  { id: "kharlamov2", hero: "kharlamov", ic: "❄️", name: "Валерий Харламов", tag: "После аварии",
    text: "В 1976 году он попал в тяжёлую автокатастрофу: перелом рёбер, ноги, сотрясение. Говорили, что он не вернётся. Он восстановился и уже через несколько месяцев снова вышел на лёд, а в составе сборной играл ещё пять лет.",
    line: "Восстановление — тоже тренировка, просто другого объёма." },
  { id: "kasparov1", hero: "kasparov", ic: "♟", name: "Гарри Каспаров", tag: "Шахматист в спортзале",
    text: "Он плавал, бегал и работал с тренером по физподготовке — и объяснял это просто: к шестому часу партии проигрывает тот, у кого раньше кончается кислород. Многолетнее первое место в шахматах он связывал в том числе с тем, что держал себя в форме физически.",
    line: "Голова работает ровно столько, сколько позволяет тело." },
  { id: "riner1", hero: "riner", ic: "🥋", name: "Тедди Ринер", tag: "Десять лет без поражений",
    text: "Французский дзюдоист не проигрывал почти десять лет — 154 схватки подряд. На вопрос о секрете отвечал, что никакого секрета нет: он приходит в зал, когда хочется и когда не хочется, и делает одно и то же больше двадцати лет подряд.",
    line: "Серия ломается в тот день, когда вы решили, что один раз можно." },
  { id: "sumo1", hero: "sumo", ic: "🍚", name: "Школа сумо", tag: "День расписан целиком",
    text: "В японской школе сумо день борца размечен по часам: подъём затемно, тренировка натощак, еда, сон, снова работа. Новички обслуживают старших и тренируются дольше всех. Система жёсткая, но она даёт то, ради чего существует: привычку, которая не зависит от желания.",
    line: "Когда распорядок решён заранее, воля расходуется на работу." },
  { id: "shaolin1", hero: "shaolin", ic: "🏯", name: "Шаолиньские монахи", tag: "Одно движение годами",
    text: "В монастырской традиции ученик может месяцами отрабатывать одну стойку, прежде чем ему покажут следующую. Со стороны выглядит бессмысленно. Смысл в том, что к моменту, когда движение становится автоматическим, тело уже перестроено под него.",
    line: "Скучный повтор меняет тело. Новое упражнение только развлекает." },
  { id: "pacquiao2", hero: "pacquiao", ic: "🥋", name: "Мэнни Пакьяо", tag: "Две тысячи раундов",
    text: "Он начинал в шестнадцать, весил сорок с небольшим килограммов и подкладывал груз в карманы, чтобы пройти взвешивание. Чемпионом он стал в восьми весовых категориях — случай единственный в истории. Между этими двумя фактами — двадцать лет ежедневной работы.",
    line: "Между «слишком лёгкий» и «чемпион» лежат только годы работы." },
  { id: "sandow1", hero: "sandow", ic: "🗿", name: "Евгений Сандов", tag: "Он придумал бодибилдинг",
    text: "Выходец из Кёнигсберга, он первым стал показывать не подъём тяжестей, а само тело — позировать, объяснять, издавать журнал с программами. Его статуэтка до сих пор вручается победителю «Мистера Олимпия». Он же первым начал продавать домашние снаряды для занятий без зала.",
    line: "Домашние занятия — не компромисс. С них всё и началось." },
  { id: "anderson1", hero: "anderson", ic: "🐂", name: "Пол Андерсон", tag: "Приседания в яме",
    text: "Американский тяжелоатлет пятидесятых тренировался во дворе: выкопал яму, вставал в неё со штангой и каждый день подсыпал немного земли, уменьшая глубину. Так он месяцами наращивал амплитуду приседа. Олимпийское золото он взял, тренируясь практически во дворе дома.",
    line: "Прогресс — это крошечная добавка каждый день, а не скачок." },
  { id: "alekseev1", hero: "alekseev", ic: "🛢", name: "Василий Алексеев", tag: "Восемьдесят рекордов",
    text: "Он установил около восьмидесяти мировых рекордов, прибавляя иногда по полкилограмма — за это его упрекали, говорили, что он тянет деньги за каждый рекорд. Он отвечал, что смысл не в деньгах: мелкий шаг надёжнее, его тело успевает принять, а большой прыжок кончается травмой.",
    line: "Маленькая прибавка, которую тело принимает, лучше героической." },
  { id: "alekseev2", hero: "alekseev", ic: "🛢", name: "Василий Алексеев", tag: "Тренировка в реке",
    text: "Часть работы он делал в воде: заходил в реку и выполнял движения с сопротивлением, берёг суставы. Для семидесятых это выглядело чудачеством. Сегодня это обычная восстановительная практика, которую применяют профессиональные команды.",
    line: "Беречь суставы — не слабость, а способ тренироваться дольше." },
  { id: "suleymanoglu1", hero: "suleymanoglu", ic: "🪶", name: "Наим Сулейманоглу", tag: "Карманный Геркулес",
    text: "Рост метр сорок семь, вес около шестидесяти — и три олимпийских золота подряд. Он поднимал над головой втрое больше собственного веса. Когда говорят, что для силы нужны габариты, его имя — лучший ответ: решает не размер, а отношение силы к весу.",
    line: "Сила измеряется не килограммами тела, а тем, что вы с ним делаете." },
  { id: "bjornsson1", hero: "bjornsson", ic: "🪓", name: "Хафтор Бьёрнссон", tag: "От баскетбола к силе",
    text: "Он играл в баскетбол за сборную Исландии, но травма колена закрыла карьеру. Вместо того чтобы уйти из спорта, он перешёл в силовой экстрим и через несколько лет стал сильнейшим человеком планеты, а позже побил рекорд в становой тяге.",
    line: "Травма закрывает один путь, а не все сразу." },
  { id: "shaw1", hero: "shaw", ic: "🧰", name: "Брайан Шоу", tag: "Он считал калории как работу",
    text: "Четырёхкратный сильнейший человек мира относился к еде как к части тренировки: до десяти тысяч калорий в день, по графику, даже когда не хотелось. Говорил, что самое тяжёлое в его режиме — не штанга, а обязанность есть тогда, когда аппетита нет.",
    line: "Восстановление требует такой же дисциплины, как работа." },
  { id: "kazmaier1", hero: "kazmaier", ic: "💥", name: "Билл Казмайер", tag: "Сила без техники не живёт",
    text: "Один из сильнейших людей восьмидесятых, он рано травмировал спину и позже говорил молодым одно и то же: вес растёт быстрее, чем связки успевают за ним. Карьеру ему укоротила не нехватка силы, а спешка в наборе весов.",
    line: "Связки отстают от мышц. Поэтому вес добавляют медленно." },
  { id: "columbu1", hero: "columbu", ic: "🥖", name: "Франко Коломбо", tag: "Пастух, боксёр, чемпион",
    text: "Сардинский пастух, потом боксёр, потом силач, потом «Мистер Олимпия» — и всё это при росте метр шестьдесят пять. Параллельно он выучился на врача-хиропрактика. Арнольд называл его самым упрямым человеком из всех, кого знал.",
    line: "Невысокий рост мешает в картинке, а не в работе." },
  { id: "oliva1", hero: "oliva", ic: "🌴", name: "Серджио Олива", tag: "Он работал в литейном цехе",
    text: "Кубинец, бежавший из страны, он работал в чикагском литейном цеху и тренировался после смены. Титул «Мистера Олимпия» он взял трижды, ни разу не бросив основную работу. Арнольд говорил, что единственный человек, рядом с которым он чувствовал себя маленьким, — это Олива.",
    line: "Основная работа не мешает. Мешает решение, что времени нет." },
  { id: "yates1", hero: "yates", ic: "🌑", name: "Дориан Йейтс", tag: "Один подход до отказа",
    text: "Шестикратный «Мистер Олимпия» тренировался меньше всех: короткие сессии, один по-настоящему тяжёлый подход на упражнение, доведённый до полного отказа. Он доказывал, что важен не объём, а то, насколько честно сделан решающий подход.",
    line: "Один честный подход стоит трёх, сделанных вполсилы." },
  { id: "yates2", hero: "yates", ic: "🌑", name: "Дориан Йейтс", tag: "Подвал вместо модного зала",
    text: "Он готовился к титулам в тёмном подвальном зале в Бирмингеме, где не было ничего, кроме железа, и куда не заходили туристы. Говорил, что обстановка не должна отвлекать: чем меньше вокруг лишнего, тем проще сосредоточиться на работе.",
    line: "Хороший зал — тот, где ничто не мешает работать." },
  { id: "zane1", hero: "zane", ic: "📐", name: "Фрэнк Зейн", tag: "Учитель математики",
    text: "Он преподавал математику в школе и тренировался после уроков. Его подход был таким же: расчёт, измерения, пропорции вместо погони за массой. Он трижды выигрывал «Олимпию», будучи заметно легче соперников, потому что строил не объём, а форму.",
    line: "Считайте не килограммы, а то, что реально меняется." },
  { id: "lalanne1", hero: "lalanne", ic: "🧓", name: "Джек Лалэйн", tag: "Отжимания в семьдесят",
    text: "Американец, открывший один из первых фитнес-клубов, тренировался ежедневно до глубокой старости и каждый день рождения устраивал себе испытание. В семьдесят он проплыл с грузом больше полутора километров со связанными руками и ногами, буксируя лодки.",
    line: "Возраст меняет вид нагрузки, а не необходимость в ней." },
  { id: "lalanne2", hero: "lalanne", ic: "🧓", name: "Джек Лалэйн", tag: "Он не ждал настроения",
    text: "Его спрашивали, любит ли он тренироваться. Он отвечал честно: ненавижу. И добавлял, что любит то, как себя чувствует после, и именно за это идёт в зал каждый день. Шестьдесят лет без перерыва — на нелюбви к процессу и уважении к результату.",
    line: "Любить процесс необязательно. Достаточно приходить." },
  { id: "cruise1", hero: "cruise", ic: "🪂", name: "Том Круз", tag: "Год ради одного прыжка",
    text: "Ради затяжного прыжка в «Миссия невыполнима» он совершил больше сотни тренировочных прыжков, а ради сцены с задержкой дыхания под водой готовился месяцами и удерживал дыхание около шести минут. Он настаивает на своих трюках и говорит, что отличие видно в кадре.",
    line: "Одна сцена стоит сотни повторов. Как и один рекорд." },
  { id: "cruise2", hero: "cruise", ic: "🪂", name: "Том Круз", tag: "Перелом и съёмка",
    text: "На съёмках в Лондоне он прыгнул между крышами, ударился о стену и сломал лодыжку — кадр с этим прыжком остался в фильме. После операции и восстановления он вернулся к тому же трюку и переснял его. Ему было за пятьдесят.",
    line: "Неудачная попытка не закрывает упражнение. Она его откладывает." },
  { id: "keanu1", hero: "keanu", ic: "🔫", name: "Киану Ривз", tag: "Тысячи повторов на стрельбище",
    text: "К роли в «Джоне Уике» он месяцами отрабатывал перезарядку, стрельбу и дзюдо по несколько часов в день. Инструкторы говорили, что он доводил каждое движение до автоматизма — поэтому в фильме почти нет монтажных склеек: он действительно всё это делает.",
    line: "Автоматизм появляется только после скучного числа повторов." },
  { id: "keanu2", hero: "keanu", ic: "🔫", name: "Киану Ривз", tag: "«Матрица» на больной шее",
    text: "Перед съёмками «Матрицы» ему сделали операцию на позвоночнике, и врачи запрещали нагрузки. Он всё равно прошёл четырёхмесячную подготовку по боевым искусствам, частично в корсете, подстраивая движения под ограничения, а не отказываясь от них.",
    line: "Ограничение меняет упражнение, а не отменяет тренировку." },
  { id: "bale1", hero: "bale", ic: "⚖️", name: "Кристиан Бэйл", tag: "Опасная игра с весом",
    text: "Он худел до крайности ради «Машиниста», потом набирал массу ради «Бэтмена», потом снова менялся для других ролей. Сам он позже говорил, что это вредно и что больше так делать не будет: тело отвечает на такие качели здоровьем, а не только формой.",
    line: "Резкие качели веса впечатляют на экране и вредят в жизни." },
  { id: "hemsworth1", hero: "hemsworth", ic: "🔨", name: "Крис Хемсворт", tag: "Тор без магии",
    text: "Для роли он набрал около двадцати килограммов мышц за несколько месяцев: силовые дважды в день, питание по расписанию, сон как часть плана. Он честно говорит, что это была работа на полную занятость, оплачиваемая студией, а не то, что можно повторить между делом.",
    line: "Киношные превращения — это работа на полный день, а не хобби." },
  { id: "cavill1", hero: "cavill", ic: "🦸", name: "Генри Кавилл", tag: "Он начинал полным подростком",
    text: "В школе его дразнили за лишний вес и звали Толстым Кавиллом. Форму для роли Супермена он набирал годами, а не перед съёмками, и говорил, что за спиной у него больше неудачных попыток похудеть, чем удачных — просто он не прекращал пробовать.",
    line: "Неудачные подходы к привычке не считаются, если вы вернулись." },
  { id: "lundgren1", hero: "lundgren", ic: "🧪", name: "Дольф Лундгрен", tag: "Магистр химии и каратист",
    text: "До кино он получил степень по химической инженерии и был чемпионом Европы по киокушинкай. Тренировки он не бросил и в шестьдесят с лишним, но сменил подход: меньше веса, больше подвижности и суставов, потому что цель изменилась.",
    line: "С возрастом меняется не наличие тренировок, а их содержание." },
  { id: "vandamme1", hero: "vandamme", ic: "🦵", name: "Жан-Клод Ван Дамм", tag: "Шпагат десять лет",
    text: "Его визитная карточка — шпагат между двумя опорами — результат растяжки, которую он делал с двенадцати лет ежедневно. Он рассказывал, что первые годы не мог сесть даже наполовину и прибавлял буквально по сантиметру в месяц.",
    line: "Гибкость набирается сантиметрами и теряется за недели." },
  { id: "norris1", hero: "norris", ic: "🧔", name: "Чак Норрис", tag: "Его били в начале",
    text: "В начале карьеры он проигрывал турнир за турниром и всерьёз думал бросить. Вместо этого он стал разбирать каждое поражение и менять технику под себя. Шесть лет спустя он был непобеждённым чемпионом мира в среднем весе.",
    line: "Серия поражений — это данные. Бросить — единственный способ проиграть." },
  { id: "donnie1", hero: "donnie", ic: "🐲", name: "Донни Йен", tag: "Каждый день с четырёх лет",
    text: "Его мать была мастером ушу и ставила ему технику с раннего детства: занятия до школы и после, без выходных. Он говорит, что к моменту, когда он попал в кино, тело уже двадцать лет делало одно и то же — поэтому хореография давалась легко.",
    line: "Лёгкость в движении — это отложенный результат долгих лет." },
  { id: "tonyjaa1", hero: "tonyjaa", ic: "🐘", name: "Тони Джаа", tag: "Тренировки в поле",
    text: "Он вырос в деревне на северо-востоке Таиланда, тренировался на рисовых полях и в реке, повторяя движения из фильмов, которые смотрел в соседнем городе. Никакого зала, никаких матов. Его трюки в кино снимались без тросов и компьютерной графики.",
    line: "Для начала хватает земли под ногами и желания повторять." },
  { id: "yeoh1", hero: "yeoh", ic: "💃", name: "Мишель Йео", tag: "Из балета в трюки",
    text: "Она училась на балерину, но травма позвоночника закрыла эту дорогу. Она ушла в кино и стала выполнять трюки сама, без дублёров, на уровне партнёров-каскадёров — потому что балетная база дала ей контроль над телом, которого не было у других.",
    line: "Старая база не пропадает: она становится фундаментом нового." },
  { id: "crews1", hero: "crews", ic: "🎺", name: "Терри Крюс", tag: "Зал в шесть утра двадцать лет",
    text: "Бывший игрок НФЛ, он после спорта не бросил тренировки, а сделал их частью дня: подъём около пяти, зал, потом работа. Говорит, что это дешевле терапии и что главное правило — приходить, даже если планируешь сделать мало.",
    line: "Правило простое: прийти. Объём обсудим на месте." },
  { id: "theron1", hero: "theron", ic: "🩰", name: "Шарлиз Терон", tag: "Колено вместо балета",
    text: "Она готовилась к карьере балерины, но травма колена всё отменила. Позже для ролей ей приходилось осваивать единоборства уже взрослой, с нуля, набивая синяки. Она говорит, что балет дал не растяжку, а привычку повторять одно и то же без жалоб.",
    line: "Главное, что даёт любая школа, — привычка к повторению." },
  { id: "murakami1", hero: "murakami", ic: "✍️", name: "Харуки Мураками", tag: "Писатель, который бегает",
    text: "Он начал бегать в тридцать три, когда бросил курить и закрыл свой джаз-бар ради письма. С тех пор — по десять километров почти каждый день и по марафону в год, больше сорока лет подряд. Он считает, что роман пишется не талантом, а способностью выдерживать однообразие.",
    line: "Выносливость в работе и в теле — это одна и та же привычка." },
  { id: "murakami2", hero: "murakami", ic: "✍️", name: "Харуки Мураками", tag: "Не выкладываться до конца",
    text: "Его правило: останавливаться, пока ещё хочется продолжать. И в письме, и в беге он не доводит себя до отвращения, потому что завтра нужно вернуться. Сорок лет ежедневной работы держатся именно на этом — не на героизме, а на умении вовремя остановиться.",
    line: "Оставьте немного сил на завтра — завтра тоже нужно прийти." },
  { id: "tolstoy1", hero: "tolstoy", ic: "📖", name: "Лев Толстой", tag: "Турник в усадьбе",
    text: "Он занимался гимнастикой почти до конца жизни: турник, гантели, долгие прогулки, работа в поле наравне с крестьянами. В семьдесят с лишним он учился ездить на велосипеде, чем смешил знакомых. Движение он считал обязанностью, а не развлечением.",
    line: "Возраст — повод сменить нагрузку, а не бросить её." },
  { id: "tolstoy2", hero: "tolstoy", ic: "📖", name: "Лев Толстой", tag: "Дневник как контроль",
    text: "Он десятилетиями вёл дневник, где отмечал в том числе и физические занятия, и собственные срывы. Не для красоты: записанное труднее забыть и легче исправить. Привычка вести учёт помогала ему возвращаться к режиму после каждого перерыва.",
    line: "Записанный срыв — шаг к возвращению. Забытый — шаг к привычке срываться." },
  { id: "pavlov1", hero: "pavlov", ic: "🔬", name: "Иван Павлов", tag: "Нобелевский лауреат на городках",
    text: "Он до старости играл в городки, ездил на велосипеде и работал в саду, а летом устраивал обязательные «физкультурные» дни для сотрудников лаборатории. Считал, что голова учёного держится ровно столько, сколько держится его тело.",
    line: "Мозгу нужна нагрузка на тело — это не метафора." },
  { id: "amosov1", hero: "amosov", ic: "❤️", name: "Николай Амосов", tag: "Тысяча движений",
    text: "Знаменитый хирург и автор системы «режим ограничений и нагрузок» делал ежедневно около тысячи движений гимнастики, бегал и работал до глубокой старости. Свою систему он придумал не из теории: в пятьдесят у него начались проблемы со здоровьем, и он решил проверить её на себе.",
    line: "Систему проверяют на себе и годами, а не неделю." },
  { id: "amosov2", hero: "amosov", ic: "❤️", name: "Николай Амосов", tag: "Эксперимент в восемьдесят",
    text: "После операции на сердце он не снизил нагрузку, а увеличил: нарастил число движений и продолжал наблюдать за собой, записывая результаты. Он честно писал и о том, что эксперимент не всё изменил — но отказываться от движения считал худшим из решений.",
    line: "Движение не отменяет возраст, но меняет то, как он проходит." },
  { id: "plisetskaya1", hero: "plisetskaya", ic: "🦢", name: "Майя Плисецкая", tag: "Станок каждый день",
    text: "Она танцевала на сцене до шестидесяти с лишним и каждый день начинала с класса у станка — тех же упражнений, что делала в училище. Говорила, что пропустить день можно, но тело об этом сообщит через три, а зритель заметит через неделю.",
    line: "День без занятий тело прощает. Неделю — уже нет." },
  { id: "plisetskaya2", hero: "plisetskaya", ic: "🦢", name: "Майя Плисецкая", tag: "Её главный ответ",
    text: "Когда её спрашивали, как держать форму, она отвечала коротко: «Сижу не жрамши». Грубовато, но честно — она признавала, что всю жизнь ограничивала себя в еде и что никакой другой тайны у неё нет. Остальное делала ежедневная работа.",
    line: "Питание решает не меньше, чем тренировка. И так же ежедневно." },
  { id: "baryshnikov1", hero: "baryshnikov", ic: "🎭", name: "Михаил Барышников", tag: "Колени после тридцати",
    text: "К тридцати годам его колени были изношены настолько, что классический репертуар стал опасен. Вместо ухода он перешёл в современный танец, где движения другие, и продолжал выступать десятилетиями. Он поменял не цель, а способ её достигать.",
    line: "Если движение перестало подходить — меняют движение, а не цель." },
  { id: "gagarin1", hero: "gagarin", ic: "🚀", name: "Юрий Гагарин", tag: "Отбор по физподготовке",
    text: "В отряд космонавтов отбирали не столько по знаниям, сколько по тому, как человек переносит перегрузки, вращение и изоляцию. Кандидаты ежедневно занимались гимнастикой, бегом и прыжками с парашютом. Полёт длился сто восемь минут, подготовка — годы.",
    line: "Короткое событие обеспечивается длинной подготовкой." },
  { id: "iss1", hero: "iss", ic: "🛰", name: "Экипажи МКС", tag: "Два часа в день, обязательно",
    text: "В невесомости мышцы и кости теряют массу очень быстро, поэтому тренировка на станции — не желание, а пункт расписания: около двух часов ежедневно на беговой дорожке и силовом тренажёре, с ремнями вместо веса. Пропуск означает, что на Земле человек не сможет ходить.",
    line: "Там, где нагрузка исчезает, тело разбирает себя за недели." },
  { id: "franklin1", hero: "franklin", ic: "🕯", name: "Бенджамин Франклин", tag: "Тринадцать добродетелей",
    text: "Он составил список качеств, которые хотел в себе развить, и завёл таблицу: каждый вечер отмечал, где сорвался. Работал по одной добродетели в неделю, по кругу. Он честно писал, что идеала так и не достиг — но стал заметно лучше, чем был бы без таблицы.",
    line: "Таблица с отметками честнее памяти и работает годами." },
  { id: "kant1", hero: "kant", ic: "⏰", name: "Иммануил Кант", tag: "По нему сверяли часы",
    text: "Он выходил на прогулку в одно и то же время настолько точно, что соседи, по легенде, проверяли по нему часы. Прогулка была не прихотью, а частью режима, который он держал десятилетиями — при слабом здоровье это позволило ему работать до старости.",
    line: "Одно и то же время каждый день снимает вопрос «идти ли сегодня»." },
  { id: "suvorov1", hero: "suvorov", ic: "🎖", name: "Александр Суворов", tag: "Он был болезненным ребёнком",
    text: "В детстве он был слабым и часто болел, и отец не видел в нём будущего военного. Он начал обливаться холодной водой, спать на жёстком и много ходить пешком — и так всю жизнь. В шестьдесят с лишним он водил войска через Альпы.",
    line: "Слабое здоровье в начале — не приговор, а стартовая точка." },
];

/* Одна тренировка — одна новая запись. Раньше шаг рос (1,2,3…8,10,12,14…),
   и после восьмой тренировки записи открывались всё реже. */
var LEGEND_AT = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154];
